### ISSUE TITLE
[TypeScript] Wrong type for parse function in 0.4.25

### ISSUE THREAD

**Issue by WolfWalter** [catamphetamine/libphonenumber-js#103]
The type for the parse function seems to be wrong. According to the readme the option object should be ok:
> typescript: src/pages/share/share.ts, line: xxxx
            Argument of type '{ country: { default: string; }; }' is not assignable to parameter of type '"BT" | "LT" |
            "MM" | "GG" | "MA" | "SX" | "SL" | "GA" | "GE" | "IN" | "NE" | "GT" | "MX" | "AD" |...'. Object literal may
            only specify known properties, and 'country' does not exist in type '"BT" | "LT" | "MM" | "GG" | "MA" | "SX"
            | "SL" | "GA" | "GE" | "IN" | "NE" | "GT" | "MX" | "AD" |...'.
Lxxxx:      let parsedNumber = parse(telNumber, {country: {default: 'DE'}});

**Comment by catamphetamine** [comment]
Well, I don't know typescript so you can fix it yourself if you want

**Comment by catamphetamine** [comment]
Closing for now, create a PR if you manage to fix it.
