### ISSUE TITLE
How to create North America only metadata?

### ISSUE THREAD

**Issue by mohsen1** [catamphetamine/libphonenumber-js#106]
Our input is limited to North America (+1) numbers. I want to reduce the meta data to that. Is that possible?

**Comment by catamphetamine** [comment]
North America is no special than any other region in the world.
You can generate metadata yourself the way it's described in the docs.

**Comment by catamphetamine** [comment]
The manual:
https://github.com/catamphetamine/libphonenumber-js#customizing-metadata
