### ISSUE TITLE
Inconsistent format output between format() and asYouType

### ISSUE THREAD

**Issue by mrmoneyboy** [catamphetamine/libphonenumber-js#112]
Hi,

this: `new asYouType("DE").input("03012345678")` results in `"030 12345678"`, while this: `format("03012345678", "DE", "National")` results in `"03012345678"`.
Why is the space between the area code and phone number missing when using `format()`?

Thanks in advance for the support.

**Comment by catamphetamine** [comment]
I guess that's because "as you type" and "format" have different inner implementation.
If you spot a divergence from the Google's original demo then you may reopen this.

**Comment by catamphetamine** [comment]
A guess is that "as you type" is looser and "format" is strict

**Comment by mrmoneyboy** [comment]
Ok thanks again for the reply. I'll look deeper into that.
