### ISSUE TITLE
local numbers not formatted correctly in AU

### ISSUE THREAD

**Issue by caesay** [catamphetamine/libphonenumber-js#119]
In AU most numbers are 9 digits following a 0.
Ex. 0555 555 555

google's libphonenumber formats this Intl as "+61 555 555 555" (correct) while this library formats it as "+61 0555555555". Removing the leading 0 causes it to be formatted correctly in this library as well, but that's not how they will be entered by users.

**Comment by catamphetamine** [comment]
Give a link to the google demo result

**Comment by caesay** [comment]
https://libphonenumber.appspot.com/phonenumberparser?number=0406123456&country=AU

**Comment by catamphetamine** [comment]
The demo formats as the google one does

```
Format


AU

0406123456
National: 0406 123 456
International: +61 406 123 456
International plaintext: +61406123456
```

**Comment by caesay** [comment]
Ah, didn't know you had a demo as well. I just installed the most recent version a few hours ago and it would only work if i omitted the leading zero - i'll create a small repo app if i can.
