### ISSUE TITLE
Angular-cli (using webpack) and extended metadata

### ISSUE THREAD

**Issue by natcohen** [catamphetamine/libphonenumber-js#134]
I'm trying to set up my angular 4 app with extended metadata (I need to have phone type for all countries). I have installed the library using `npm install libphonenumber-js --save` and have created the `metadata.full.json` as explained in your documentation (`libphonenumber-generate-metadata src/assets/json/metadata.full.json --extended`).

I then tried this:

```
import { parseCustom, isValidNumberCustom } from 'libphonenumber-js'
import metadata from '../../assets/json/metadata.full.json'
```

But I get an error with the `parseCustom` and `isValidNumberCustom` (`Module has no exported member parseCustom and isValidNumberCustom`) and `Cannot find module ../../assets/json/metadata.full.json` (I've checked and rechecked the path).

I also tried this:
```
import { parse as parseCustom,  isValidNumber as isValidNumberCustom} from 'libphonenumber-js/custom'
import metadata from '../../assets/json/metadata.full.json'
```
I got rid of the first error (`Module has no exported member parseCustom and isValidNumberCustom`) but still have the second one `Cannot find module ../../assets/json/metadata.full.json`

I've check the metadata file and it's a pure json file. It starts like this: `{"country_phone_code_to_countries":{"1":["US","AG","AI","AS"....` So I'm wondering how can it be considered as a module?

**Comment by catamphetamine** [comment]
> and have created the metadata.full.json as explained in your documentation 

It's already part of the distributed package

> But I get an error with the parseCustom and isValidNumberCustom (Module has no exported member parseCustom and isValidNumberCustom)

That means that your bundler doesn't support ES6 modules so use the `/custom` one instead (which you do).

> Cannot find module ../../assets/json/metadata.full.json

That's something with your setup, unrelated to this library

**Comment by natcohen** [comment]
Wow, that was quick!

Just to make sure I understand... Can I simply install the library using: `npm install libphonenumber-js --save` and then import: `import { getNumberType } from 'libphonenumber-js'` and will get everything I need (get all phone types of all countries)?

The `metadata` part is not very clear to me...

Thanks again for your support and this awesome library!

**Comment by catamphetamine** [comment]
https://github.com/catamphetamine/libphonenumber-js#customizing-metadata

By default a user gets everything except advanced phone number validation and phone number type detection.
Therefore, use `libphonenumber-js/metadata.full.json` and the "Custom" functions.

**Comment by natcohen** [comment]
`import metadata from 'libphonenumber-js/metadata.full.json'` returns the `Cannot find module` error as well.

I didn't setup anything, I just used angular-cli which is based on ember-cli and uses WebPack.

**Comment by catamphetamine** [comment]
Then it's something with your setup because the file is there, in the package

**Comment by natcohen** [comment]
Ok, got it working by adding `declare module '*.json' { const value: any; export default value; }` to my `typing.d.ts`.

Now I'm facing another issue... 

```
import { getNumberType as getNumberTypeCustom } from 'libphonenumber-js'
import metadata from 'libphonenumber-js/metadata.full.json'

export const getNumberType = (...args) => getNumberTypeCustom(...args, metadata);
```

`getNumberTypeCustom(...args, metadata)` returns `Expected 1-2 arguments, but got a minimum of 1`

Any idea?

**Comment by catamphetamine** [comment]
Post the actual code

**Comment by natcohen** [comment]
This all what I do:
```
import { getNumberType as getNumberTypeCustom } from 'libphonenumber-js'
import metadata from 'libphonenumber-js/metadata.full.json'

export const getNumberType = (...args) => getNumberTypeCustom(...args, metadata);
```

in one of my angular component.

**Comment by natcohen** [comment]
Please note that I'm trying to use `getNumberType` and not `parse` like in your example.

**Comment by catamphetamine** [comment]
Post the full stack trace

**Comment by catamphetamine** [comment]
And the full code

**Comment by catamphetamine** [comment]
Of the component

**Comment by natcohen** [comment]
´´´
import { OnInit, Component} from '@angular/core';
import { USER } from '../app.config';

import { getNumberType as getNumberTypeCustom } from 'libphonenumber-js'
import metadata from 'libphonenumber-js/metadata.full.json'

export const getNumberType = (...args) => getNumberTypeCustom(...args, metadata);

@Component({
    selector: 'welcome',
    providers: [],
    templateUrl: 'welcome.component.html'
})
export class WelcomeComponent implements OnInit {

    public user:any = USER;

    constructor() {

    }

    ngOnInit() {
        console.log('welcome');
    }

    ngOnDestroy(){
        console.log("destroyed");
    }
}
´´´

and when I try to build it with `ng build`, I get the following error:
```
ERROR in /Users/myname/WebApps/myapp/client/src/app/components/welcome.component.ts (7,43): Supplied parameters do not match any signature of call target.
```

I don't know what else I could give you...

**Comment by catamphetamine** [comment]
Well, that seems like a TypeScript definitions issue: it searches for the `getNumberTypeCustom()` definition and doesn't find any I guess.
Anyway, I'm not affiliated with TypeScript in any way.

**Comment by natcohen** [comment]
OK! Will try with stackoverflow...

Thank you so much for your help!

**Comment by natcohen** [comment]
Found an easy fix by casting the function like this:

`export const getNumberType = (...args) => (<any>getNumberTypeCustom)(...args, metadata);`
