### ISSUE TITLE
Cursor is not positioned properly in Android devices

### ISSUE THREAD

**Issue by Subha** [catamphetamine/libphonenumber-js#140]
I am having issues in "As you type" in Android chrome browser as mentioned in issue #105.

Since the below issue is closed

https://github.com/catamphetamine/libphonenumber-js/issues/105#issuecomment-321501098.

I am creating a new one. Could you help to resolve this issue.

Many Thanks

**Comment by catamphetamine** [comment]
Reopened the original issue with a workaround for your case.
