### ISSUE TITLE
Doesn't accept non-english keyboard 

### ISSUE THREAD

**Issue by FakhruddinAbdi** [catamphetamine/libphonenumber-js#141]
Why you doesn't support non-english keyboard whilst the original libphonenumber library do.

Its really deal breaker.

**Comment by catamphetamine** [comment]
You mean letter phone numbers?
Because I don't see any point in them.

**Comment by catamphetamine** [comment]
Or is your mobile phone number something like `(123) BIG BOSS`

**Comment by FakhruddinAbdi** [comment]
Yes phone numbers

why?
the package is about supporting multi-national phone numbers
So you should expect to enter non-english uni-code in the input

like this

+٤٤٢٣٢٣٢٣٤

**Comment by FakhruddinAbdi** [comment]
They are supporting this 
Please check this http://libphonenumber.appspot.com/

**Comment by catamphetamine** [comment]
I don't see any value in numbers like `+٤٤٢٣٢٣٢٣٤`.
What is that anyway. Some jewish word I guess. Can't they just use digits.

**Comment by FakhruddinAbdi** [comment]
Its arabic characters dear 
+٤٤٣٤٥٦٧٨ = +44345678

**Comment by catamphetamine** [comment]
So in Arabic countries they don't use "arabic digits"?
So weird.

**Comment by FakhruddinAbdi** [comment]
Its numbers,  and many people use them when filling number inputs

**Comment by catamphetamine** [comment]
Ok, if you wish so.
I'll add them.
Are all phone numbers in Iraq written like that?

**Comment by FakhruddinAbdi** [comment]
<img width="704" alt="screen shot 2017-10-10 at 15 33 14" src="https://user-images.githubusercontent.com/8319873/31385488-4a90d2f4-add0-11e7-8f82-f22d50dacdba.png">

**Comment by catamphetamine** [comment]
Ok, whatever, I guess you're right, how am I supposed to know living in Russia

**Comment by FakhruddinAbdi** [comment]
In Iraq , Iran, Saudia  and many countries in Middle-east 

I will appreciate it dear

**Comment by FakhruddinAbdi** [comment]
Its not just about arabic unicodes 
I think you may need to include all numbers in all unicodes 
To make really international package 

I may could help if you want

**Comment by catamphetamine** [comment]
Yeah, sure, it shouldn't be fixed for just arabic then, it should be fixed for all of them.
I'll investigate Google's code later today about that.

**Comment by catamphetamine** [comment]
This turned out to be a bug in `react-phone-number-input` and it has been fixed.
See the updated demo there.

**Comment by FakhruddinAbdi** [comment]
wow .. its working like a charm .
Thanks for your update
