### ISSUE TITLE
Phone Number of 10+ digits  is accepted

### ISSUE THREAD

**Issue by Anoop-Goudar** [catamphetamine/libphonenumber-js#143]
`isValidNumber('01234567890', 'IN'))` returns true => valid
`isValidNumber('+911234567890', 'IN'))` returns true => valid
But I feel below example should not valid.
`isValidNumber('1234567890123', 'IN'))` returns true => not valid

Kindly suggest.

**Comment by catamphetamine** [comment]
What exactly are you asking

**Comment by catamphetamine** [comment]
I updated the "Bug reporting" section.
Read there.
https://github.com/catamphetamine/libphonenumber-js#bug-reporting
