### ISSUE TITLE
GitHub demo shows incorrect results for national number validity

### ISSUE THREAD

**Issue by s01ipsist** [catamphetamine/libphonenumber-js#144]
https://catamphetamine.github.io/libphonenumber-js/

When entering a number into the "As You Type" section, entering a National format number will present as `Valid: false` even though the same number in International format will present as `Valid: true`. Both these should present as valid.

http://libphonenumber.appspot.com/phonenumberparser?number=2133734253&country=US

International format
![image](https://user-images.githubusercontent.com/13267/31647996-329bc2e4-b357-11e7-96b0-d290409e5508.png)

National format
![image](https://user-images.githubusercontent.com/13267/31647989-28aec506-b357-11e7-8222-e710b4fb2f76.png)

I believe this is because of the line
```
Valid: {String(libphonenumber.isValidNumber(this.state.value))}
```
which should instead use the two argument version to ensure it is parsed first. Perhaps

```
Valid: {String(libphonenumber.isValidNumber(this.state.value, this.state.country))}
```

**Comment by catamphetamine** [comment]
Indeed, but with this country variable:

```js
Valid: {String(libphonenumber.isValidNumber(this.state.value, as_you_type.country))}
```

Fixed the demo and released new version.
