### ISSUE TITLE
Cannot call isValidNumber() function with 2 parameters

### ISSUE THREAD

**Issue by vlaxos713** [catamphetamine/libphonenumber-js#145]
Is there a reason why the following line is commented out on "index.d.ts" file?
`//export interface CountryCode extends String { }`

In order to call isValidNumber(phone, country) i need to define my country parameter as type "any" instead of a "string"

**Comment by catamphetamine** [comment]
You can create a Pull Request if you feel like you know what you're doing.
I myself do not support TypeScript, it's purely contributor-maintained.

**Comment by vlaxos713** [comment]
Thanks for the reply, I will do some tests later on and maybe open one.
