### ISSUE TITLE
Typescript typing - enhancement

### ISSUE THREAD

**Issue by waratah** [catamphetamine/libphonenumber-js#146]
Can I request that the following:

   'International' | 'International_plaintext' | 'National'

be extracted to a separate type in index.d.ts so that I can refer to it in my code.  (ie same as CountryCode type).  I have copied and pasted it for my code in the meantime.

Thanks

**Comment by catamphetamine** [comment]
TypeScript support for this library is entirely community-driven. I myself don't use TypeScript.
