### ISSUE TITLE
Validation issue in German mobile numbers

### ISSUE THREAD

**Issue by nirangad** [catamphetamine/libphonenumber-js#148]
Please check following link with this invalid German number **+49163651068**

[Google Demo](https://libphonenumber.appspot.com/phonenumberparser?number=%2B49163651068&country=DE)

> Result from isValidNumber() | false

The output from this [demo page](https://catamphetamine.github.io/libphonenumber-js/)

Value: +49163651068
Default country: US
Actual country: DE
Valid: true
National: 163651068

**Comment by catamphetamine** [comment]
Read the "Bug reporting" section one more time
https://github.com/catamphetamine/libphonenumber-js#bug-reporting

**Comment by catamphetamine** [comment]
I added notes about validation to the demo page.
