### ISSUE TITLE
asYouType with custom template

### ISSUE THREAD

**Issue by tallen11** [catamphetamine/libphonenumber-js#151]
Any way to change to asYouType template? In my app I've the country code in a separate box from the rest of the phone number. I'd like the rest of the number to be formatted according to the currently entered country, but don't want any + or country code at the front of it. Is this possible?

**Comment by catamphetamine** [comment]
it's not clear what's your point here

**Comment by tallen11** [comment]
I want to use the asYouType formatter to format my text as I type WITHOUT having the +country code at the beginning.

**Comment by catamphetamine** [comment]
Then just trim it
