### ISSUE TITLE
getNumberType() returns undefined for Irish phone numbers

### ISSUE THREAD

**Issue by danielsefton** [catamphetamine/libphonenumber-js#152]
When I pass Irish phone numbers to libphonenumber-js, for example +353 872037131, I get "undefined" from getNumberType().

However, when you enter this number into the official libphonenumber demo, it works and returns MOBILE:

http://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

I am calling the function like this:

`var numberType = libphonenumber.getNumberType('872037131', 'IE');`

Any ideas? Thanks in advance.

**Comment by catamphetamine** [comment]
This is because you're not using the "full" metadat.

**Comment by danielsefton** [comment]
Thanks for the quick reply, do you have an example of how to load the metadata into getNumberType with the standalone bundle? I could not find anything in the readme other than how to generate the metadata.

**Comment by catamphetamine** [comment]
Added the example to the README.
It's the same as for the other "custom" functions.

**Comment by danielsefton** [comment]
Has to be the quickest reply ever :) Thanks for the addition, however I'm trying to use the library without a bundler/ES6 (under "Standalone"). I can't figure out how to load the metadata into the function without using "import".

**Comment by catamphetamine** [comment]
Don't understand what you're talking about.
"Custom" functions need no bundler usage.

**Comment by danielsefton** [comment]
Assuming I'm calling it standalone like so, what do I pass to "metadata"?

`libphonenumber.getNumberTypeCustom(number.phone, number.country, metadata)`

**Comment by catamphetamine** [comment]
`require('libphonenumber-js/metadata-full')`

**Comment by danielsefton** [comment]
Yeah but that still requires NodeJs, is there a way with plain JavaScript? Thanks for you time.

**Comment by catamphetamine** [comment]
Oh, so you're using it in a browser.
Of course.
And without a bundler.
I see now.
But how do you include the library itself on a page.
If you include it as is then it comes bundled with the default metadata.
If you want to include the full metadata then you should use a bundler to exclude the default metadata and to add the full metadata.
If you just included the full metadata on a page then there would be 2 metadatas loaded: the default one and the full one.
As for including the full metadata, perhaps there's no way to do that in a web browser.
You could copy that file to your project and make it into a js file by doing `window.fullMetadata = { ... }` and then including it on a page.

**Comment by danielsefton** [comment]
Yeah I'm building a browser bundle with "npm run browser-build" and including the JS in the page.

Yes you are right, it didn't cross my mind to paste the metadata into a JS variable, it works fine, thanks!
