### ISSUE TITLE
variable type error: solution proposal.

### ISSUE THREAD

**Issue by luisgagocasas** [catamphetamine/libphonenumber-js#155]
I found an error that was presented using webpack and angular2.
is the next

![upload 3](https://user-images.githubusercontent.com/4383323/33333358-a5e2dc94-d434-11e7-8d5d-eca783477945.png)

node_modules/libphonenumber-js/index.d.ts

![captura de pantalla de 2017-11-28 12-07-39](https://user-images.githubusercontent.com/4383323/33333431-d7e569aa-d434-11e7-89cb-574f25a0221a.png)

![captura de pantalla de 2017-11-28 12-07-53](https://user-images.githubusercontent.com/4383323/33333440-db84a2b0-d434-11e7-8a3e-8603dab26bea.png)

Changing the type of variable to any

version: "libphonenumber-js": "^0.4.42"

I hope I have helped. Greetings.

**Comment by catamphetamine** [comment]
But "any" could be a string or a number which is not correct.
I'm not myself familiar with TypeScript.

https://blog.mariusschulz.com/2017/02/24/typescript-2-2-the-object-type

> TypeScript 2.2 introduces a new type called object. It represents any non-primitive type. The following types are considered to be primitive types in JavaScript:
boolean
number
string
symbol
null
undefined

I guess your TypeScript version is old.

**Comment by luisgagocasas** [comment]
you have all the reason update the version and it is solved.
