### ISSUE TITLE
THANK YOU!

### ISSUE THREAD

**Issue by mercmobily** [catamphetamine/libphonenumber-js#156]
Can I just say:

                      *** THANK YOU ***
                      *** THANK YOU ***
                      *** THANK YOU ***
                      *** THANK YOU ***
                      *** THANK YOU ***

For this wonderful gift?

**Comment by catamphetamine** [comment]
Ha ha, ok )

**Comment by mercmobily** [comment]
You didn't just write this life-saving gem... you also maintain it actively, keep the issue list under check, and help people out. My hat off... and thank you again!
