### ISSUE TITLE
Export some metadata

### ISSUE THREAD

**Issue by chamini2** [catamphetamine/libphonenumber-js#157]
I was wondering if we could expose some metadata to use on our side. For example, when asking users for their phone number, I want to give an input like:

<img width="321" alt="screen shot 2017-12-15 at 12 51 35" src="https://user-images.githubusercontent.com/2745502/34051931-b3bd2846-e196-11e7-9403-7d3371d9cbb6.png">

So I need a list of all possible country codes. I can just download it from somewhere else, but it would be great if I could just reuse the one bundled in libphonenumber, I'm sure you know every bit counts.

**Comment by catamphetamine** [comment]
https://unpkg.com/libphonenumber-js@0.4.41/metadata.min.json

```js
{
"country_phone_code_to_countries": {
"1": [
"US",
"AG",
"AI",
"AS",
"BB",
"BM",
"BS",
"CA",
"DM",
"DO",
"GD",
"GU",
"JM",
"KN",
"KY",
"LC",
"MP",
"MS",
"PR",
"SX",
"TC",
"TT",
"VC",
"VG",
"VI"
],
"7": [
"RU",
"KZ"
],
```

**Comment by chamini2** [comment]
But that means I would download the metadata twice, right? Once with `libphonenumber-js` and once with unpkg?

**Comment by catamphetamine** [comment]
require(libphonenumber-js/metadata.min.json)

**Comment by amsul** [comment]
Hey @catamphetamine!

Along the same lines..Is it possible to export the `exampleNumber` fields from the XML metadata to include in the JSON?

It's for a similar use case as above where the placeholder text uses a dummy phone number as an example.

**Comment by catamphetamine** [comment]
I decided not to use "example phone numbers" in this library because it doesn't enforce any specific phone number format.
You can extract your own examples from Google's metadata
https://github.com/catamphetamine/libphonenumber-js/blob/master/PhoneNumberMetadata.xml

**Comment by amsul** [comment]
@catamphetamine wouldn't the format be simple enough to figure out given the country code? Or am I misunderstanding what you mean?

**Comment by catamphetamine** [comment]
> wouldn't the format be simple enough to figure out given the country code? Or am I misunderstanding what you mean?

I don't see what you mean

**Comment by amsul** [comment]
I'm just confused by what you mean by

> it doesn't enforce any specific phone number format

**Comment by catamphetamine** [comment]
Any valid phone number will do

**Comment by amsul** [comment]
I think there's a bit of miscommunication going on here.

What I'd like is a way to be able to get an example phone number based on the country. It would allow me to do something like this:

```jsx
const countryCode = 'CA'
const exampleNumber = libphonenumber.getExampleNumber(countryCode)
const formattedExampleNumber = libphonenumber.format(exampleNumber, countryCode, 'International')

// With React:
<Input placeholder={formattedExampleNumber} />
```

I hope that clarifies it a bit..

Is that something within the scope of this library? Considering the metadata exists in the XML, it would be very useful to have it in the JSON as well.

**Comment by catamphetamine** [comment]
> Is that something within the scope of this library? Considering the metadata exists in the XML, it would be very useful to have it in the JSON as well.

It's not a part of this library but you can extract that data from Google's XML file and do it as you've written above.

**Comment by amsul** [comment]
Would you be interested in a PR that adds a `metadata.with-examples.json` file?

I would imagine this is quite a common scenario for people and maintaining a separate copy would be kinda of a pain.

It also doesn't seem like there are any docs on how to build a custom metadata file that would include the examples: https://github.com/catamphetamine/libphonenumber-js#customizing-metadata

**Comment by catamphetamine** [comment]
Currently I don't think that examples would be of any value so I'd not add them to the library in its current state.
There are no docs on parsing Google's metadata because there isn't meant to be any.
Refer to this file as a reference:
https://github.com/catamphetamine/libphonenumber-js/blob/master/source/tools/generate.js

**Comment by amsul** [comment]
Okay thank you for all the info! I appreciate it.

It's unfortunate that I showed you a scenario where it has value but you still believe it doesn't add value.

Thanks anyways.

**Comment by catamphetamine** [comment]
Yeah, because "value" is a purely subjective thing and what's value for one is of no value for the other.

**Comment by amsul** [comment]
Fair enough :)

I figured an extra JSON file does no harm..one simply just doesn't use it if they don't find it valuable. But it's your call! Fine with your decision.

**Comment by catamphetamine** [comment]
Well, we could find a compromise: I could generate an `examples.json` file having a shape:

```js
{
'RU': '88005553535' (or should it be formatted),
...
}
```

Will that do?

**Comment by catamphetamine** [comment]
Actually, it would be:

```js
{
  'RU':
  {
    mobile: '88005553535',
    uan: '013427612374',
    fixed: '34167023561094875042398'
  },
  ...
}
```

**Comment by catamphetamine** [comment]
And you will have to distill this examples file yourself taking just what's gonna be used.
Will that be suitable?

**Comment by amsul** [comment]
Wow that would actually be even better than the solution I was suggesting!

It'd be *amazing* to have this 🙏

**Comment by catamphetamine** [comment]
The new release has `examples.mobile.json` in the root

**Comment by catamphetamine** [comment]
Not all countries have mobile phone number examples though, e.g. "TA"

**Comment by catamphetamine** [comment]
Released `libphonenumber-js@0.4.46` which has a workaround for "TA" by substituting mobile example with fixed line example.

**Comment by catamphetamine** [comment]
TA is "Tristan_da_Cunha"
```xml
    <!-- Tristan da Cunha -->
    <!-- Calling code and formatting shared with 'SH' -->
    <territory id="TA" countryCode="290" internationalPrefix="00">
      <references>
        <sourceUrl>http://www.itu.int/oth/T02020000AF/en</sourceUrl>
      </references>
      <generalDesc>
        <nationalNumberPattern>8\d{3}</nationalNumberPattern>
      </generalDesc>
      <fixedLine>
        <possibleLengths national="4"/>
        <exampleNumber>8999</exampleNumber>
        <nationalNumberPattern>8\d{3}</nationalNumberPattern>
      </fixedLine>
    </territory>
```

**Comment by amsul** [comment]
@catamphetamine thank you for making this happen so fast!

And thanks again for the awesome library 💯
