### ISSUE TITLE
Error: US Phone Numbers with 11 digits are shown as Valid

### ISSUE THREAD

**Issue by estebanav** [catamphetamine/libphonenumber-js#159]
I've found that US Phone Numbers with 11 digits are parsed as OK.

I added two tests to validate 2 invalid US Phone Numbers. The first one is show as OK but the second is shown as valid when it shouldn't be. There are no 11 digits phone numbers in the US.

See PR at: [https://github.com/catamphetamine/libphonenumber-js/pull/158](https://github.com/catamphetamine/libphonenumber-js/pull/158)

**Comment by catamphetamine** [comment]
So are both phone numbers correct or is only one of them correct?

**Comment by catamphetamine** [comment]
I guess both of them are invalid

**Comment by catamphetamine** [comment]
I see, so both of them are incorrect but only the second test is incorrect

**Comment by catamphetamine** [comment]
Yeah, the parsing algorythm is currently stripping national prefix without checking whether the initial number was an international one.
That's a small fix.

**Comment by catamphetamine** [comment]
By the way, google's libphonenumber does allow both numbers:
https://libphonenumber.appspot.com/phonenumberparser?number=%2B1+213+215+5230
https://libphonenumber.appspot.com/phonenumberparser?number=%2B1+1213+215+5230
And it's the same for google's "as you type".
So, apparently, here's the point of divergence from the google's original implementation.
I guess that's ok, and while Google is more forgiving with phone number input this library should be more strict I guess.
As far as I've read on the internets it's invalid for an international phone number to contain any national prefixes.
So, I'm making this change.

**Comment by catamphetamine** [comment]
released `libphonenumber-js@0.4.48`

**Comment by estebanav** [comment]
Thanks so much @catamphetamine you didn't give me time to answer your question ha! :)
