### ISSUE TITLE
Missing dashes from phone numbers

### ISSUE THREAD

**Issue by darkenvy** [catamphetamine/libphonenumber-js#163]
I noticed that dashes are missing from US/CA phone numbers (and potentially other countries as well). 

Instead of: `702-555-1234` it is `702 555 1234`. 

Is there a option I am missing?

**Comment by catamphetamine** [comment]
Read the bug reporting section
https://github.com/catamphetamine/libphonenumber-js#bug-reporting
If the issue persists then repost it as described
