### ISSUE TITLE
Recommendation: Remove spaces from your module names.

### ISSUE THREAD

**Issue by waynebloss** [catamphetamine/libphonenumber-js#164]
Hello again and thanks for all your work.

I briefly looked at your code just now to see how everything works and to see if it will be easy to maintain by myself if necessary. Then I saw that you have spaces in some of your module names. This is very non-standard and causes me to be concerned. I could imagine this breaking some build tool-chain given how complex things like WebPack are these days.

Other than possibly breaking something, I think it is generally frowned upon in most programming languages but in JavaScript specifically I cannot find a style-guide that recommends it.

**Comment by catamphetamine** [comment]
Oh, well, ok.
