### ISSUE TITLE
Regression in from commit "misc refactoring"

### ISSUE THREAD

**Issue by atsu85** [catamphetamine/libphonenumber-js#174]
Example:
`isValidNumber('+3725555555');`
returns true with version 1.0.8 (and also previous commit before ["misc refactoring" commit](https://github.com/catamphetamine/libphonenumber-js/commit/44af3e346581b61ee4960d531bcfc2e24c52b3da)
I suspect that regression could be related to 
`i <= MAX_LENGTH_COUNTRY_CODE`
that doesn't consider the fact, that number can contain "+" sign

**Comment by catamphetamine** [comment]
Oh, man, true, you nailed it..
Will fix now.

**Comment by catamphetamine** [comment]
Should add your test too.

**Comment by catamphetamine** [comment]
Released `libphonenumber-js@1.0.13` with your fix.

**Comment by atsu85** [comment]
thanks for reacting so quickly!
