### ISSUE TITLE
Numbers without a leading plus are considered invalid.

### ISSUE THREAD

**Issue by jpickwell** [catamphetamine/libphonenumber-js#179]
Passing a number like `18772155230` into `isValidNumberCustom('18772155230', 'US', <US-only metadata>)`, the function returns `false` even though Google's library will indicate that it's valid.

https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

**Comment by catamphetamine** [comment]
Did you pass `--extended` flag.
It works with `metadata.full.json`.
Your metadata is not complete.

![image](https://user-images.githubusercontent.com/477167/36038132-d9babb48-0dcf-11e8-86ac-b3a731d173d6.png)

**Comment by catamphetamine** [comment]
Oh, `isValidNumber`, maybe I'll test that one instead

**Comment by catamphetamine** [comment]
Still valid.

![image](https://user-images.githubusercontent.com/477167/36038186-0be5444e-0dd0-11e8-96d7-88aadce07d83.png)

**Comment by jpickwell** [comment]
Let me try rebuilding my metadata.

**Comment by jpickwell** [comment]
Sorry about that. I completely forgot about updating the metadata after updating to a newer version of this library. I was already using the `--extended` flag, but was using outdated metadata. Thanks for the quick response.

**Comment by catamphetamine** [comment]
Ouch, you got me.
The recent refactor added `possibleLengths` property and I didn't think about backwards-compatibility.
It's true that some users generated metadata with the old version and don't re-generate metadata upon publishing the project.
Maybe I should add some backwards compatibility.

**Comment by catamphetamine** [comment]
(added backwards compatibility)
