### ISSUE TITLE
[1.0.18, 10.0.19] [Fixed] UglifyJS Unexpected character '`'

### ISSUE THREAD

**Issue by asaarnak** [catamphetamine/libphonenumber-js#183]
from UglifyJs
Unexpected character '`' [./node_modules/libphonenumber-js/index.es6.js:84,0]

Currently seems like char ` isn't supported by UglifyJS.

**Comment by catamphetamine** [comment]
Oh, another bug.
Ok, thx, will fix now.

**Comment by asaarnak** [comment]
Thanks!

**Comment by catamphetamine** [comment]
Released `libphonenumber-js@1.0.21`

**Comment by catamphetamine** [comment]
I'll reopen this for a while because I've been getting messages from other users about this issue
