### ISSUE TITLE
Unable to parse US Toll-Free numbers into National Format

### ISSUE THREAD

**Issue by kwoumn3** [catamphetamine/libphonenumber-js#184]
I'm not sure if this is the expected functionality, but US toll free numbers are unable to be parsed into National format.

So for example if I do `format(parse("+18001000066", 'National')`, I get back an empty object.

Is it possible for US toll free numbers to be parsed as National numbers?

**Comment by catamphetamine** [comment]
See the bug reporting section of the readme.
https://github.com/catamphetamine/libphonenumber-js#bug-reporting

**Comment by catamphetamine** [comment]
You can reopen the issue after that.
