### ISSUE TITLE
isValidNumber is not working correctly

### ISSUE THREAD

**Issue by sarbjeet-cmsDev** [catamphetamine/libphonenumber-js#186]
-I am using 

isValidNumber('9803528785',"IN")) === true
isValidNumber('98035287855',"IN")) === true
2nd also showing true but it must be invalid because 11 char long

**Comment by catamphetamine** [comment]
See https://github.com/catamphetamine/libphonenumber-js#bug-reporting

**Comment by sarbjeet-cmsDev** [comment]
I got you, but I am doing  like this
import metadata from '../../../metadata/metadata.min.json';
export const format = (...args) => formatCustom(...args, metadata)
format({ phone: val, country: 'IN' })
its keep saying metadatais required

can you help me in this?

**Comment by catamphetamine** [comment]
See if the metadata exists. Console.log(metadata)

**Comment by sarbjeet-cmsDev** [comment]
I make it work by format({ phone: val, country: 'IN' },metadata)

I looked into your function, but you have to make it autofetch data from your build, I saw its exiting over there

**Comment by catamphetamine** [comment]
Don’t understand what you said

**Comment by sinneren** [comment]
How to use isValidNumber, getCountryCallingCode etc, except AsYouType, parse, format in standalone?
Because when I call `new libphonenumber.isValidNumber(number)` it returned blank function named **o {}**. Similar with another methods.

**Comment by catamphetamine** [comment]
See the examples in the readme.
`isValidNumber` is not a class, neither are other functions.

**Comment by sinneren** [comment]
А, мы же можем по-русски. Я не понял, извини, но нужна помощь. В ридми это часть API. Так как его использовать? Не часть класса, то isValidNumber() будет is not defined.

**Comment by catamphetamine** [comment]
В ридми — весь АПИ. Как использовать — там написано. Вы опять пишете
непонятно.

**Comment by sinneren** [comment]
А может просто Readme такое? Да, я понял, что нужно перегенерить metadata с флагом --extended. Не помогло. Даже размер файла бандла не изменился. Я запустил батник обновления и снова перегенерил только full версию с флагом --extended. Это тоже не помогло. Я полез в index.es6 и index.common и заменил там metadata.min на metadata.full. Да, теперь бандл стал больше. И даже на валидацию отдаёт иной результат. Правда, всё равно это что-то несуразное. По остальным методам, так же отдаётся функция. Так как мне сделать бандл, чтобы необходимый функционал наконец заработал?

**Comment by catamphetamine** [comment]
> А может просто Readme такое? 
Нет, вам следует поработать над более ясным выражением собственных мыслей.

> Правда, всё равно это что-то несуразное.
Несуразное — это то, что пишете вы.

> Так как мне сделать бандл, чтобы необходимый функционал наконец заработал?
Научиться мыслить логически.
