### ISSUE TITLE
Uncaught Error: Metadata is required

### ISSUE THREAD

**Issue by sktzofrenic** [catamphetamine/libphonenumber-js#191]
I'm really not sure what this means. The error is thrown when I use the following code: 

`format(parse(this.number, 'US').phone, 'US', 'E.164')`

And some additional information:

`this.number === '3832918231'`

`"libphonenumber-js": "^1.1.3",`

What metadata do I need that I'm not providing?

**Comment by catamphetamine** [comment]
Most probably you're importing `parse` and `format` from `libphonenumber-js/custom` and not supplying metadata.
Use the default ones.
And also this way is better:
`format(parse(this.number), 'E.164')`

**Comment by catamphetamine** [comment]
`Metadata is required` means that you're not passing the correct arguments to functions (maybe missing arguments or too much arguments)

**Comment by sktzofrenic** [comment]
Here is my import statement:

`import { format, parse, isValidNumber } from 'libphonenumber-js'`

I also updated the function to `format(parse(this.number), 'E.164')` but am still receiving the same error. 

The part of your response that I don't understand is:

> and not supplying metadata.

I would be happy to supply the metadata, I just am not sure what that is or how to supply it. 

Thank you for your time in responding to this. I appreciate it.

**Comment by catamphetamine** [comment]
Your import looks ok.
And the function looks ok too.
Then I don't know why is it throwing the error.
Could be anything.
If other people report the same error then reopen this issue.

**Comment by catamphetamine** [comment]
You may also try importing functions from `/custom`

```js
import { parse, format } from `libphonenumber-js/custom`
import metadata from `libphonenumber/metadata.full.json`
format(parse(this.number, metadata), 'E.164', metadata)
```

**Comment by sktzofrenic** [comment]
Thanks again for your efforts here. Ultimately this may be an issue with ParcelJS and how it bundles files and because I couldn't resolve it I had to switch to a different library.

**Comment by catamphetamine** [comment]
Oh, parcel.js.
I guess it doesn't import `json` files then.
I.e. in the source it's `import metadata from './metadata.min'` and it can't resolve it to `./metadata.min.json`.
That's a possibility though - I didn't use ParcelJS.
