### ISSUE TITLE
Number of digits in the mobile phone number using the country code

### ISSUE THREAD

**Issue by isopen** [catamphetamine/libphonenumber-js#196]
Is there an opportunity in the library?
Eg:
`libphonenumber.getCountDigitsByCountry('US')`
On the output: the number of digits in the phone number by county code. Perhaps in the form of a structure, if several.

**Comment by catamphetamine** [comment]
There's no such thing, digits vary by their number.

**Comment by isopen** [comment]
Is there such a thing?
https://github.com/giggsey/libphonenumber-for-php/blob/master/docs/PhoneNumberUtil.md#getexamplenumber

**Comment by catamphetamine** [comment]
Yes, there are example numbers.
See the readme.

**Comment by isopen** [comment]
Prompt please function realizing it

**Comment by catamphetamine** [comment]
There's no such function.
See the Examples section of the readme.

**Comment by isopen** [comment]
It would have been nice if she had been.

**Comment by catamphetamine** [comment]
You can write your own.

```js
import examples from `libphonenumber-js/examples.mobile`.
const example = country => examples[country]
```

**Comment by isopen** [comment]
@catamphetamine Thanks.

I think it will be easier to expand this (for the library user)
libphonenumber.as_you_type('EN')

**Comment by catamphetamine** [comment]
> I think it will be easier to expand this (for the library user)
libphonenumber.as_you_type('EN')

Not understand

**Comment by isopen** [comment]
Add field here
http://joxi.ru/52ayQ3OSG1B8X2
eg: "example"

**Comment by catamphetamine** [comment]
Ah, I see.
Well, not going to add such feature to "as you type" because not everyone needs that, but you can implement it using a function.
Ok.

**Comment by isopen** [comment]
This can make life easier when building masks for input fields.

**Comment by isopen** [comment]
Netherlands Antilles
`AN or ANT`
No in the examples `examples.mobile`

**Comment by catamphetamine** [comment]
> Netherlands Antilles
AN or ANT
No in the examples examples.mobile

No such country.

**Comment by isopen** [comment]
I agree, but the code is still available for many.

**Comment by catamphetamine** [comment]
You can create an issue in Google's repo if you want.

**Comment by isopen** [comment]
I agree, but before I write to them. It is necessary to check whether they take into account the existing codes of countries that are in the status of not employed.
I suggest you understand this and discuss with google.

**Comment by catamphetamine** [comment]
> I agree, but before I write to them. It is necessary to check whether they take into account the existing codes of countries that are in the status of not employed.
I suggest you understand this and discuss with google.

If you think that something is missing from the metadata you can create an issue in Google's repo.

**Comment by isopen** [comment]
I thought you were doing a serious library. I think you understand the essence of the problem and discuss it with google much easier.

**Comment by catamphetamine** [comment]
> I thought you were doing a serious library. I think you understand the essence of the problem and discuss it with google much easier.

If you want something you discuss it with Google yourself.
Why do you think anybody will do your own work for you.

**Comment by isopen** [comment]
So this is your library. I offered you a certain stage of evolution. Why do you resist I do not know :)

**Comment by catamphetamine** [comment]
> So this is your library. I offered you a certain stage of evolution. Why do you resist I do not know :)

No, you didn't offer anything.
That's me who's offering.
I not only offered you a solution but also a certain stage of evolution.
Why do you resist I do not know.

**Comment by isopen** [comment]
Okay. Here's the answer.
for example js:
`examples[country] == undefined`

**Comment by catamphetamine** [comment]
Because `country` doesn't exist

**Comment by isopen** [comment]
I offered you the stage of evolution, but you again resist.
Do as you like :) the question is closed
