### ISSUE TITLE
libphonenumber not defined

### ISSUE THREAD

**Issue by andrewlphilpott** [catamphetamine/libphonenumber-js#197]
I'm dynamically loading in the `/bundle/libphonenumber-js.min.js` in an app and I'm running into a weird issue.

Locally, I'm able to use `window.libphonenumber` after the script is loaded. On my stage server, though, `window.libphonenumber` is always undefined. I threw a test `console.log()` into the js file to make sure it’s being loaded and executed and it is, so I’m not really sure what the issue might be.

I found [this issue](https://github.com/catamphetamine/libphonenumber-js/issues/14) and tried using `window['libphonenumber-js']` as well, but that is also undefined.

**Comment by catamphetamine** [comment]
> I'm dynamically loading in the /bundle/libphonenumber-js.min.js in an app

I guess your issue may be related to the word "dynamically" somehow.
Try the usual `<script src>`.

And make sure you're using the same file in both cases.
If that's the case then I don't know why wouldn't it work because it should.
So I guess you're on your own here.

**Comment by andrewlphilpott** [comment]
For what it’s worth, I found the issue. The app I’m working on gets embedded into various other platforms and the one that I was testing on had jQuery loaded while locally I am not using jQuery. That somehow messed things up but I was able to work around it.

**Comment by catamphetamine** [comment]
Hmm.
Ok, I dunno, Webpack generates the so-called UMD bundle by wrapping the code with all sorts of `if (window) window.libphonenumber = ... else if (global) global.libphonenumber = ... else if ...`.
I'd advice everyone to use bundlers instead of script src.

**Comment by andrewlphilpott** [comment]
Yeah, that makes sense and I normally would use a bundler. In this situation, though, I need the initial load of this app to be as small as possible and users only need to validate their phone number once and then never again. So rather than making them download things they won’t use, I’m just loading the script when they actually need it.

**Comment by catamphetamine** [comment]
I see.
Well, that's one working way to do it.
Another (very advanced) way is to "code-split" the app so that `libphonenumber-js` "chunk" is only loaded on certain routes.

**Comment by andrewlphilpott** [comment]
Ah yeah, that’s not really an option on this app. It doesn’t actually have routes, it just shows views based on an API response.
