### ISSUE TITLE
React-Native: Error: undefined is not a function (evaluating \'text[typeof Symbol === \'function\' ? Symbol.iterator : \'@@iterator\']()\')

### ISSUE THREAD

**Issue by edolix** [catamphetamine/libphonenumber-js#198]
Hi, i'm using this lib in a ReactNative App and methods `parse` and `format` catch this error:

```
Error: undefined is not a function (evaluating \'text[typeof Symbol === \'function\' ? Symbol.iterator : \'@@iterator\']()\') drop_and_substitute_characters
....
```

How i'm using lib:

```
import { parse, format } from 'libphonenumber-js'

let p = parse('8 (800) 555 35 35', 'RU')
console.log(p)
```

Installed from: `npm install libphonenumber-js`

I'm doing something wrong?
Thanks!

**Comment by catamphetamine** [comment]
Seems that `Symbol.iterator` is `undefined` - that's what the error says.
It's not supposed to be `undefined`.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator
You can check that by manually editing the js file in node_modules by adding a console.log.
Perhaps your ES6 Symbol polyfill is not complete: `Symbol` seems to be defined but seems that it's not the ES6 `Symbol`.

**Comment by catamphetamine** [comment]
You can try using `import 'babel-polyfill'` or something like that (as the first line of your program).

**Comment by catamphetamine** [comment]
Or, actually, my previous comment was incorrect: the `Symbol` polyfill seems fine but `text[Symbol.iterator]` is `undefined` for some reason.

**Comment by edolix** [comment]
@catamphetamine thanks for the quick reply!

`Symbol.iterator` is equal to `'@@iterator'`, `text` is a string (the input number) so: `'8 (800) 555 35 35'`.

**Comment by edolix** [comment]
Is the package updated on `npm`?

**Comment by catamphetamine** [comment]
Yeah, seems that you're not in a full ES6 environment.
Are you using Babel?

**Comment by catamphetamine** [comment]
> Is the package updated on npm?

What do you mean?

**Comment by edolix** [comment]
> Yeah, seems that you're not in a full ES6 environment.
> Are you using Babel?

I'm on ReactNative but it seems that `Symbol` are not fully supported by RN. 

https://github.com/facebook/react-native/issues/15902

**Comment by catamphetamine** [comment]
Well, I could look into a way of polyfilling symbol iterator somehow.
I'll post if I find something.

**Comment by edolix** [comment]
I found a workaround here https://github.com/facebook/react-native/issues/15902#issuecomment-375521246.
It seems to work!

**Comment by catamphetamine** [comment]
@edolix Yeah, that's one way to do it, and actually it's better in a sense that other libraries relying on Symbol don't break.

The other thing is that I found a way to bypass `Symbol.iterator` in the code and released a new version `libphonenumber-js@1.1.6`. If you feel like trying it out (while temporarily reverting your `core-js` fix) then you could do that. Otherwise your present workaround seems fine.

**Comment by catamphetamine** [comment]
CC @sachinB94 @m-hosoi ^^^^^^^

**Comment by edolix** [comment]
> If you feel like trying it out ....

SUPER! I'll try it tomorrow for sure 👍 

@catamphetamine thanks again for your help!

**Comment by edolix** [comment]
@catamphetamine `v1.1.6` it works without any workaround! Thanks!
