### ISSUE TITLE
Different behavior in node vs webpack

### ISSUE THREAD

**Issue by rytakahashi** [catamphetamine/libphonenumber-js#200]
Hello,

It seems the package recommends importing using the following method (link [here](https://github.com/catamphetamine/libphonenumber-js#usage)).

```javascript
import { parse, format, AsYouType } from 'libphonenumber-js'
```

However, in medium to large files, `parse` and `format` tend to be common variable names so we are importing as follows.

```javascript
import libphonenumber from 'libphonenumber-js'
```

This seems to work fine in node but in the browser (webpack) `libphonenumber` is undefined and we need to import as follows.

```javascript
import * as libphonenumber from 'libphonenumber-js'
```

If I were to guess, it seems like `module.exports` is being set in the [common environment](https://github.com/catamphetamine/libphonenumber-js/blob/master/index.common.js#L6) but there is no equivalent in the es6 environment.

I am uncertain whether one method is preferred over the other, but from an API perspective I think it's a good idea to support both so the code behaves the same way in all environments.

**Comment by catamphetamine** [comment]
Use import { parse as parseNumber } from libphonenumber-js

**Comment by rytakahashi** [comment]
Thanks for the quick response, what are your thoughts on having the code behave the same way in both environments? This may confuse people in the future as well.

**Comment by catamphetamine** [comment]
> what are your thoughts on having the code behave the same way in both environments?

What do you mean?

**Comment by catamphetamine** [comment]
The browser and Node.js use different modules: Node.js uses `commonjs` folder and browsers use `modules` folder. `commonjs` is `module.exports` and `modules` are ES6 modules so there's nothing wrong about that: they have inherently different exports. The correct way is `import { parse as parsePhone } from libphonenumber-js`.

**Comment by catamphetamine** [comment]
Added `parseNumber` and `formatNumber` aliases.
https://github.com/catamphetamine/libphonenumber-js#usage

**Comment by rytakahashi** [comment]
Thanks for addressing this so quickly.
