### ISSUE TITLE
findPhoneNumbers missing typescript declaration

### ISSUE THREAD

**Issue by breathe** [catamphetamine/libphonenumber-js#202]
I see a possible type declaration that is commented out in index.d.ts -- I will try that and if it works I'll submit a PR (or modify the type declaration) and attach to this ticket

**Comment by catamphetamine** [comment]
Ok

**Comment by breathe** [comment]
So — that’s weird — are you not interested in a pr?

**Comment by catamphetamine** [comment]
It's not weird.
See the "TypeScript" section of the readme.
