### ISSUE TITLE
Can't parse Armenian numbers

### ISSUE THREAD

**Issue by fxfactorial** [catamphetamine/libphonenumber-js#204]
this caused me some embarrassment: 

```
const { parseNumber } = require('libphonenumber-js');
const result = parseNumber('+374499336998');
```

And you'll see that it can't understand an Armenian phone number.
```
  "libphonenumber-js": "^1.1.10",
```

**Comment by catamphetamine** [comment]
See the bug reporting section and re-create the issue if it's valid
https://github.com/catamphetamine/libphonenumber-js#bug-reporting

**Comment by fxfactorial** [comment]
Gotcha , sorry about noise
