### ISSUE TITLE
Use custom data in react native, but give the error `Metadata is required`

### ISSUE THREAD

**Issue by annewanghy** [catamphetamine/libphonenumber-js#205]
Hi, really appreciate your library. I have a little problem in react native.

When I use the custom metadata in my project. 

Since I use typescript, so I need to write a `phonenumber.d.ts` file to declare the function(And I have found there is no `custom` folder in `node_modules/libphonenumber-js`)
```js
declare module "libphonenumber-js/custom" {
  export function isValidNumber(
    val: string,
    country?: string,
    metadata?: object
  ): boolean;
}
```
And then I use it as frontend validation
```js
import { isValidNumber } from "libphonenumber-js/custom";
import metadata from "../metadata.min.json";

if (
      rules.isValidPhoneNumber &&
      !isValidNumber(valStr, "JP", metadata)
    ) {
      return "phone_number_invalid";
}
```

the code works well but the test cases give me the error 
```
Error for phone: Error: Metadata is required
```
Each function related to phone validation will be broken due to this error,  but I don't know how to fixed it. Can you help me with that? thanks in advance : )

**Comment by catamphetamine** [comment]
`Error: Metadata is required` means that either metadata argument was not passed or it was not a valid metadata.

**Comment by catamphetamine** [comment]
I guess I should change the error message to be more descriptive.

**Comment by annewanghy** [comment]
Debugging, thank you for the quick reply!

**Comment by catamphetamine** [comment]
Version `1.1.11` has been published with more descriptive error message in case of `metadata` argument being of incorrect type.

**Comment by annewanghy** [comment]
Had solved this problem by using `const metadata = require("../metadata.min.json");` instead of `import metadata from "../metadata.min.json";` since test environment is node, so it doesn't support es6.

**Comment by catamphetamine** [comment]
So, you changed your code and it worked?
Can this issue be closed then?

**Comment by annewanghy** [comment]
Yes.
