### ISSUE TITLE
can't find some functions available in libphonenumber

### ISSUE THREAD

**Issue by salzhrani** [catamphetamine/libphonenumber-js#206]
specifically `getRegionCodeForCountryCode`, `getExampleNumberForType` and enums like `PhoneNumberFormat` and `PhoneNumberType`. I looked and searched but wasn't able to figure if they exists or not.

**Comment by catamphetamine** [comment]
There're no such functions.
For example numbers see `example.mobile.json` file.
`getRegionCodeForCountryCode` — maybe it's `getCountryCallingCode()`.
