### ISSUE TITLE
isValidNumber is not working correctly for Ukrainian numbers since v1.2

### ISSUE THREAD

**Issue by romandubrov** [catamphetamine/libphonenumber-js#210]
Hello,

it seems something got broken with new version.

// 1.1.11
isValidNumber('+380972423740') => true

// 1.2.1
isValidNumber('+380972423740') => false

Tried other countries - seems only UA was affected

UPD: link to Google's demo page: https://libphonenumber.appspot.com/phonenumberparser?number=%2B380972423740

Google's result from isValidNumber() is true

**Comment by catamphetamine** [comment]
Most likely metadata update.
Read the bug reporting section and follow the instructions.

**Comment by romandubrov** [comment]
added link to Google's demo page

**Comment by catamphetamine** [comment]
Google's demo returns `isValid() === true` because it has full metadata.
Read the "Bug reporting" section again.

**Comment by romandubrov** [comment]
so just to clarify - is this expected behaviour of libphonenumber-js since version 1.2? once again: 1.1 has different behaviour with reduced metadata

**Comment by catamphetamine** [comment]
Post the metadata piece for "UA" which passes the test on 1.1

**Comment by romandubrov** [comment]
yes, I'm referring to this default metadata bundled with npm package for 1.1.11 and 1.2.x versions respectively

**Comment by catamphetamine** [comment]
Post the metadata piece for "UA" which passes the test on 1.1.x

**Comment by romandubrov** [comment]
I suppose it's somewhere in this file https://github.com/catamphetamine/libphonenumber-js/blob/d56a24f46b53db97a83372c5436279143b025625/metadata.min.json

do you mean this piece?

```
		"UA": ["380", "[3-9]\\d{8}", [9],
			[
				["([3-9]\\d)(\\d{3})(\\d{4})", "$1 $2 $3", ["[38]9|4(?:[45][0-5]|87)|5(?:0|[67][37])|6[36-8]|7|9[1-9]", "[38]9|4(?:[45][0-5]|87)|5(?:0|6(?:3[14-7]|7)|7[37])|6[36-8]|7|9[1-9]"]],
				["([3-689]\\d{2})(\\d{3})(\\d{3})", "$1 $2 $3", ["(?:3[1-8]|4[136-8])2|5(?:[12457]2|6[24])|6(?:[12][29]|[49]2|5[24])|8[0-8]|90", "3(?:[1-46-8]2[013-9]|52)|4(?:[1378]2|62[013-9])|5(?:[12457]2|6[24])|6(?:[12][29]|[49]2|5[24])|8[0-8]|90"]],
				["([3-6]\\d{3})(\\d{5})", "$1 $2", ["3(?:[1-46-8]|5[013-9])|4(?:[137][013-9]|[45][6-9]|6|8[4-6])|5(?:[1245][013-9]|3|6[0135689]|7[4-6])|6(?:[12][13-8]|[49][013-9]|5[0135-9])", "3(?:[1-46-8](?:[013-9]|22)|5[013-9])|4(?:[137][013-9]|[45][6-9]|6(?:[013-9]|22)|8[4-6])|5(?:[1245][013-9]|3|6(?:[015689]|3[02389])|7[4-6])|6(?:[12][13-8]|[49][013-9]|5[0135-9])"]]
			], "0", "0$1"
		],
```

**Comment by catamphetamine** [comment]
Ok, sorry, I wasn't thinking straight, it is a bug indeed.
Fixed in the latest release.
Thanks.

**Comment by catamphetamine** [comment]
Слава Украине

**Comment by romandubrov** [comment]
thanks a lot!

Героям слава!
