### ISSUE TITLE
Belarusian mask doesnt parse correctly

### ISSUE THREAD

**Issue by 105th** [catamphetamine/libphonenumber-js#215]
In Belarus to call a mobile number we can use '+375' or '80'.
If i use parseNumber function with country parameter, it does not remove international mask for Belarus (+375), but replace it to 80.
`console.log(formatNumber('+375 33 381 51 66', 'BY', 'National')) // ​​​​​8 033 381-51-66​​​​​ 
console.log(formatNumber('+7 916 810 51 81', 'RU', 'National')) // ​​​​​916 810-51-81​​​​​`
For Russian number it just remove '+7' code, but for Belarus it **replace** '+375' by '80'.

Google lib links to correct parsing:
[Belarus](https://libphonenumber.appspot.com/phonenumberparser?number=%2B375+33+381+51+66)
[Russia](https://libphonenumber.appspot.com/phonenumberparser?number=%2B79168105181)

Screenshots:
![image](https://user-images.githubusercontent.com/11395678/40409866-d10e79b2-5e74-11e8-9166-6cae8d9b4aa6.png)
![image](https://user-images.githubusercontent.com/11395678/40409879-db42ab74-5e74-11e8-8420-87b3dbac622d.png)
1 - is what i inserted
2 - code
3 - is what i expected to have been parsed

**Comment by catamphetamine** [comment]
You're not using `parseNumber`, you're using `formatNumber`.
It formats the number, and does so correctly, in accordance with Google's demo (see "Formatting Results" section).

**Comment by 105th** [comment]
@catamphetamine my bad. thank you!
