### ISSUE TITLE
Clarification request from docs

### ISSUE THREAD

**Issue by jaufgang** [catamphetamine/libphonenumber-js#216]
Your documentation says:

> So, the general phone number rules for a country are mainly for phone number formatting: they dictate how different phone numbers (matching those general regular expressions) should be formatted. And parseNumber() uses only those general regular expressions (as per the reference Google's libphonenumber implementation) to perform basic phone number validation. isValidNumber(), on the other hand, is all about validation, so it digs deeper into precise regular expressions (if they're included in metadata) for possible phone numbers for a given country. And that's the difference between them: parseNumber() parses phone numbers and loosely validates them while isValidNumber() validates phone number precisely (provided the precise regular expressions are included in metadata).

> **By default those precise regular expressions aren't included in metadata** because that would cause metadata to grow twice in its size (the complete metadata size is about 145 kilobytes while the default reduced metadata size is about 77 kilobytes). If anyone needs to use (or generate) custom metadata then it's quite easy to do so: follow the instructions provided in the Customizing metadata section of this document.

But it is not entirely clear what you are saying here.  `parseNumber()` and `validateNumber()` are different because `validateNumber()` can potentially do extended checks with additional metadata, but that additional metadata is not included by default.  So without explicitly adding the extended metadata do they both just use the same general rules?  Or do they validate using different rules, just fewer differences without the extended metadata?

**Comment by catamphetamine** [comment]
> parseNumber() and validateNumber() are different because validateNumber() can potentially do extended checks with additional metadata, but that additional metadata is not included by default.

Yes, that's the point.

> So without explicitly adding the extended metadata do they both just use the same general rules?

Yes, they do.

**Comment by catamphetamine** [comment]
Updated the readme.
