### ISSUE TITLE
RFC3966 ;name:value vs ;name=value

### ISSUE THREAD

**Issue by cdunn** [catamphetamine/libphonenumber-js#217]
Came across an incompatibility with another library I was using and thinking this is a bug?

https://github.com/catamphetamine/libphonenumber-js/blob/6e6943c657da0eeb494c33b4e0381698dd0d4507/source/RFC3966.js#L16

https://www.ietf.org/rfc/rfc3966.txt
isdn-subaddress      = ";isub=" 1*uric
extension            = ";ext=" 1*phonedigit
context              = ";phone-context=" descriptor

happy to submit pr if you agree with the issue of using '=' vs ':'

**Comment by catamphetamine** [comment]
Oh.
Not sure why I did it.
Looks like a big change across several files/tests.
Thanks, I'll do it.

**Comment by catamphetamine** [comment]
Fixed in `libphonenumber-js@1.2.13`.
