### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: 

### ISSUE THREAD

**Issue by Dunstonhary** [catamphetamine/libphonenumber-js#223]
Hi,
After updating to the version (v1.2.15) - minifying the library to the production environment - it fails throwing up following error.

![screen shot 2018-06-20 at 9 36 56 pm](https://user-images.githubusercontent.com/8559068/41670624-6ed249a8-74d2-11e8-9cf9-af1b1b813eb7.png)

**Comment by catamphetamine** [comment]
Seems that character encoding is messed up in your case.
Make sure that the bundle javascript is in UTF-8 and is being included as a UTF-8 file on a page.
https://www.w3schools.com/tags/att_script_charset.asp

**Comment by Dunstonhary** [comment]
Thanks, that helped.
