### ISSUE TITLE
Can not delete phone number in US National format when the input string has 3 characters

### ISSUE THREAD

**Issue by nguyennb9** [catamphetamine/libphonenumber-js#225]
I'm using AsYouType to format the input phone number, I got an error when attempting to delete phone number by press Backspace when the input string has 3 characters.

Check out the gif and the code below:
![asyoutype-error](https://user-images.githubusercontent.com/12994001/41952232-121446ae-79f9-11e8-9bea-eb9d98a1e354.gif)

`new AsYouType('US').input(value)`

**Comment by catamphetamine** [comment]
This library doesn't provide any input components, it just provides a set of javascript functions.

**Comment by whimsicaldreamer** [comment]
@catamphetamine I too am facing this issue. Probably can you guide us in how we should deal with this with some kind of examples.

**Comment by catamphetamine** [comment]
@whimsicaldreamer This library doesn't provide any UI components.

**Comment by catamphetamine** [comment]
@whimsicaldreamer I didn't have such an issue in my input component.

**Comment by whimsicaldreamer** [comment]
@catamphetamine may be you could explain us what you have been trying to do here: https://github.com/catamphetamine/react-phone-number-input/blob/master/source/InputBasic.js#L34

**Comment by catamphetamine** [comment]
@whimsicaldreamer Well, ok, I did encounter a similar bug, and that was because in `onChange` I parsed the whole input and then re-formatted it.
```js
<input onChange={ value => this.setState({ value: format(parse(value)) }) }/>
```
So because a brace is not a significant character `(123)` -> `(123` was parsed to `123` and then re-formatted back to `(123)` so it was as if Backspace "didn't work" on braces.

The described use case is for `parse`/`format` though, not for "as you type" to which the OP referred.

**Comment by nguyennb9** [comment]
Yeah, the code comment has the [well explained here.](https://github.com/catamphetamine/react-phone-number-input/blob/master/source/InputBasic.js#L34).

@whimsicaldreamer  And with AsYouType, you only apply it when the input contains more than 3 characters, maybe this regex `/(.?\d){4,}/.test(input)` will help you detect when to start applying AsYouType

**Comment by whimsicaldreamer** [comment]
@catamphetamine so what to do in case of "as you type" as I am encountering the problem there. Any probable solutions or hints would be great.

**Comment by catamphetamine** [comment]
@whimsicaldreamer 
> so what to do in case of "as you type" as I am encountering the problem there.

That you'll have to figure out yourself, if you want.

**Comment by whimsicaldreamer** [comment]
@nguyennb9 any other ideas? I was hoping to keep the defaults. @catamphetamine's input component does what I actually am looking for(I suppose you too are) but for design reasons I can't use it.

**Comment by nguyennb9** [comment]
@whimsicaldreamer look at the demo: https://catamphetamine.github.io/libphonenumber-js/ he using `ReactInput` and it works just fine.

**Comment by whimsicaldreamer** [comment]
@nguyennb9 I have seen that but for

> design reasons I can't use it.

And even if I manage to modify the designs how do I turn off the country selector as I already have mine ready and in place.

**Comment by catamphetamine** [comment]
@whimsicaldreamer I didn't put it in the docs but see the source code: there is `showCountrySelect` property.
Still you could even just use CSS and `display: none` so there shouldn't be any problem.

**Comment by whimsicaldreamer** [comment]
@catamphetamine cool! I will try it out right away. But one thing that concerns me is(correct me if I am wrong), if I just do `display:none`, my app would still download the flag svgs even if I am not using them.

**Comment by catamphetamine** [comment]
@whimsicaldreamer Ok, maybe it will make sense to come up with an input component then as part of this library.
I'll release something today, and then you'll test it.

**Comment by whimsicaldreamer** [comment]
That would be awesome!! 👍

**Comment by catamphetamine** [comment]
@whimsicaldreamer 
See the related commit.
`react-phone-number-input` now has `react-phone-number-input/basic-input` export which is `<InputBasic/>`.
See the readme: https://github.com/catamphetamine/react-phone-number-input#without-country-select
I didn't test it, so you test it and see if it works.

**Comment by whimsicaldreamer** [comment]
@catamphetamine I manually tested my use cases and it turned out to be correct. Although on testing on a mobile device the input field is `text` type but other demos of `react-phone-number-input` opens up the number pad.

**Comment by whimsicaldreamer** [comment]
@catamphetamine I think you didn't update package.json to the new version number.

**Comment by catamphetamine** [comment]
@whimsicaldreamer 
I have
![image](https://user-images.githubusercontent.com/477167/42688159-e82612ca-86a3-11e8-80ac-0b493a14893d.png)
![image](https://user-images.githubusercontent.com/477167/42688236-26f4efbc-86a4-11e8-9dcd-1a78ea498c18.png)

**Comment by whimsicaldreamer** [comment]
@catamphetamine actually my IDE is spitting out:
![1](https://user-images.githubusercontent.com/8104493/42688443-e1f0c114-86b9-11e8-83aa-b2904232dfb0.png)

**Comment by whimsicaldreamer** [comment]
@catamphetamine everything is working fine now except for the above issue. Thank you for your help.

**Comment by jharsono** [comment]
@nguyennb9 I was able to work around this by only formatting once the character count is over 3 digits. What I believe to be happening is that when you hit the backspace, the field is still evaluating to 3 digits which will add the parenthesis for US format. Adding in a conditional to start formatting after 3 digits have been entered worked well for me.

**Comment by nguyennb9** [comment]
@jharsono yeah, as I said https://github.com/catamphetamine/libphonenumber-js/issues/225#issuecomment-404514300
I think we are done with this issue.

**Comment by lawnchamp** [comment]
@jharsono I am hesitant to hardcode 3 because I don't know how other countries format their phone numbers. Is the US the only country using parentheses?

**Comment by JimTeva** [comment]
@lawnchamp you are right to be hesitant https://en.wikipedia.org/wiki/National_conventions_for_writing_telephone_numbers

**Comment by aakagi** [comment]
I wasn't super happy with any of the solutions here, so here's what I ended up doing. Hopefully this helps someone out :)

```
import {
  AsYouType,
  formatIncompletePhoneNumber,
} from 'libphonenumber-js';

...

const phoneParser = new AsYouType(countryCode);

// onChangeText is a react-native TextInput thing. Same as event.target.value
const _onChangeText = (text: string) => {
  let formattedPhoneNumber = phoneParser.input(text);
  // Handle delete
  if (formattedPhoneNumber === props.value) {
    const digits = formattedPhoneNumber.replace(/\D/g,''); //strip away non-numeric characters
    const withoutLastDigit = digits.slice(0, digits.length - 1); //remove the last digit
    formattedPhoneNumber = formatIncompletePhoneNumber(withoutLastDigit, countryCode); //
  }
  onChangeText(formattedPhoneNumber);
};

```

**Comment by Morsmetus** [comment]
I am was looking for an answer but don't really like to start applying AsYouType after 3 digits..
Here is what I came up with, hope it helps others:

`export const formatPhoneNumber = (value?: string | number) => {
    if (!value) return '';
    value = value.toString();
    if (value.includes('(') && !value.includes(')')) {
        return value.replace('(', '');
    }
    return new AsYouType('US').input(value);
};
`

This is kind of a helper function I use to include in input onchange if input type is phone

**Comment by jodylane** [comment]
I  also encountered this issue & struggled with this for a minute  & didn't find any solutions I liked here. So I am posting what I ended up doing in case it helps someone else out.

```javascript
import { useState } from "react";
import { AsYouType } from "libphonenumber-js";
....
  const [cellNumber, updateCellNumber] = useState("");
  
  const formatCellNumber = (number) => {
    const asYouType = new AsYouType("US");
    asYouType.input(number);
    return asYouType;
  };
  
  const formattedCellNumber = formatCellNumber(cellNumber);
  return (
    <input
      placeholder="317-867-5309"
      name="cellphone"
      value={formattedCellNumber.formattedOutput}
      onChangeHandler={(event) => {
        let newValue = event.target.value;
        const newFormattedValue = formatCellNumber(newValue).formattedOutput;
        /*
         Makes sure a character was removed from string && the new formatted value equals current formatted
         value before removing digit
        */
        if (newValue.length < cellNumber.length && newFormattedValue === cellNumber) {
          newValue = newValue.slice(0, -1);
        }
        updateCellNumber(formatCellNumber(newValue).formattedOutput);
      }}
    />
  );
```
This fixes the original post issue however there are still issues I have observed even with this i.e.
given a string that matches this template: `x (xxx) xxx-xxxx` 
when type a string like `x (xxx) xxx-xxxx` & I place my cursor anywhere where there is a space or special character `+()-` & I remove it the number at the end of string will be removed instead with the given code its not perfect but its good enough to get me through this for now until I figure something else out

**Comment by Brandons404** [comment]
> I am was looking for an answer but don't really like to start applying AsYouType after 3 digits..
> Here is what I came up with, hope it helps others:

This fixed it for me, so thank you. But since it still returns 3 digits, which causes the field to change, triggering the event again, I added one more line to your code snippet to also delete the last digit in parenthesis:

```js
if (value.includes('(') && !value.includes(')')) {
      const tempValue = value.replace('(', '');
      return tempValue.slice(0, tempValue.length - 1);
}
```

**Comment by lucasgomsilva** [comment]
Fixed it by just applying the formatter when the inputValue was greater than 4 since no country uses an area code of 4 digits.

**Comment by edsonjuniornarvaes** [comment]
It worked for me by removing the parentheses if the country number is not valid with the number of characters.
```ts
export const formatPhoneNumber = (phoneNumber: AsYouType): string => {
    const rawNumber = phoneNumber.getChars();
    const country = phoneNumber.getCountry();

    phoneNumber.reset();

    const validCountryPhoneNumber =
	validatePhoneNumberLength(rawNumber, country) === undefined;

        if (!validCountryPhoneNumber) {
	    return phoneNumber.input(rawNumber).replace('(', '').replace(')', '');
	}

    return phoneNumber.input(rawNumber);
};
```
