### ISSUE TITLE
[DISCUSSION] Support ISO 3166 alpha 3??

### ISSUE THREAD

**Issue by bearcott** [catamphetamine/libphonenumber-js#226]
would be really cool to support ISO 3166 1 alpha 3 since some APIs request using this country code.

Here are some mappings I found:
https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes/blob/master/all/all.json

This actually also could be completely off-topic. Interested to hear y'alls thoughts

**Comment by catamphetamine** [comment]
It's not clear what you mean.
If you need ISO 3 -> ISO 2 conversion in your API then you could implement your own `getISO3ByISO2CountryCode()` function.
