### ISSUE TITLE
AsYouType.country is undefined

### ISSUE THREAD

**Issue by paschaldev** [catamphetamine/libphonenumber-js#227]
I need to get the country code of a number, I have this

```js
const asYouType = new AsYouType();
let countryCode = asYouType.input(phone)

console.log( phone, countryCode, countryCode.country )  // +2348161135238,+2348161135238, undefined
```

In the code above, the phone returns a valid Nigerian number but the `country` object property is `undefined` however, outputting just the `countryCode` variabel returns the phone number as a string and not as an object where the country property exist. 

Please help. 

I have tried different numbers, it's not just Nigerian numbers, even US numbers don't work

**Comment by catamphetamine** [comment]
AsYouType.country

**Comment by paschaldev** [comment]
I'm assigning it to a variable, does that matter?

**Comment by catamphetamine** [comment]
`.country` is a property of an instance of `AsYouType` class.
