### ISSUE TITLE
Formatting nor working?

### ISSUE THREAD

**Issue by Lennartbrugger** [catamphetamine/libphonenumber-js#228]
I'd like to format a phone number like "2133734253" with a given country to a national number like it is displayed in the example code.

```
<script src="https://unpkg.com/libphonenumber-js/bundle/libphonenumber-js.min.js"></script>
<script>
let phonenumber = new libphonenumber.formatNumber({ country: 'US', phone: '2133734253' }, 'National')
console.log(phonenumber)
</script>
```

But for some reason the **phonenumber** property is a object with no content (like **{}**).

How to fix this? Is this just an issue for me or does somebody else got this problems?

**Comment by lyngbach** [comment]
Having the same issue here with no solution so far.
