### ISSUE TITLE
Invalid German mobile phone parsing 

### ISSUE THREAD

**Issue by antonversal** [catamphetamine/libphonenumber-js#234]
version 1.3.1

```
libphonenumber.parseNumber('+4915784846111‬') => {}
```

it's valid on google
https://libphonenumber.appspot.com/phonenumberparser?number=%2B4915784846111%E2%80%AC

works ok on v 1.2.22

**Comment by catamphetamine** [comment]
Actually, you didn't put enough effort into helping me to find out the source of the bug.
You're saying that it works on `1.2.22` but you were too lazy to try it on `1.3.0`.
I'm not lazy like you so I did try it on `1.3.0` and it also works.
Then, again, if you weren't so lazy, you'd go to the commits history and see what changes were performed between those two versions and find the answer.
