### ISSUE TITLE
searchPhoneNumbers Export seems to be missing for TS

### ISSUE THREAD

**Issue by visual4** [catamphetamine/libphonenumber-js#236]
in index.d.ts there is no export for searchPhoneNumbers.
I'm not sure, if
`
export function searchPhoneNumbers(text: string, options?: CountryCode | { defaultCountry?: CountryCode }): Iterator<NumberFound>;
`
will be enough.
Cheers,
Björn

**Comment by catamphetamine** [comment]
Check if this works:

```js
export function searchPhoneNumbers(text: string, options?: CountryCode | { defaultCountry?: CountryCode }): IterableIterator<NumberFound>;
```
