### ISSUE TITLE
Moroccan mobile phone starting with 07 are considered as incorrect

### ISSUE THREAD

**Issue by RadouaneRoufid** [catamphetamine/libphonenumber-js#240]
Since 07/08/2016, Moroccan mobile operators has introduced mobile phone numbers starting with 07. In fact, `07 12 34 56 78` is considered as a valid phone number. 

But `libphonenumber-js` is considering those phone numbers as invalid.

**Comment by catamphetamine** [comment]
See this section:
https://github.com/catamphetamine/libphonenumber-js#bug-reporting
Reopen if required.
