### ISSUE TITLE
Wrong formatting for french numbers

### ISSUE THREAD

**Issue by LaVielle** [catamphetamine/libphonenumber-js#244]
Imagine a french mobile number '06 12 34 56 78'
This is the way I would type it into a phone if I wanted to call someone from France.
For calling from abroad I would type  '+33 6 12 34 56 78'
However:

- `parseNumber('06 12 34 56 78', 'FR')` returns` {country: "FR", phone: "612345678"}`, when the number should be "0612345678"
- `formatNumber({ country: 'FR', '06 12 34 56 78' }, 'International')` returns `+33 0612345678`, when the number should be +33 612345678

So I'm wondering if this is intentional or actually a mistake in the library, and I'm wondering if similar problems could exist when parsing numbers from other countries.

**Comment by catamphetamine** [comment]
> parseNumber('06 12 34 56 78', 'FR') returns {country: "FR", phone: "612345678"}, when the number should be "0612345678"

No, it returns correctly.
It returns the national (significant) number, read the README for more info.

> formatNumber({ country: 'FR', '06 12 34 56 78' }, 'International')

You're calling it incorrectly.
Read the readme for `formatNumber` for more info.

**Comment by LaVielle** [comment]
Ah correct, I see..
Then would you have any suggestions for matching phone numbers saved in international format (+33612345678) to contacts that are most likely saved in national format (0612345678).
The contact numbers could be from any country (not necessarily France) so I'm really struggling to find a way to handle that...

**Comment by catamphetamine** [comment]
Read numbers in any format and parse them.
After parsing them re-format them as proper E.164 numbers.

**Comment by LaVielle** [comment]
I mean, assuming that there is no information about the country.
Maybe you know of other libraries that somehow understand/guess a phone number's country?

**Comment by catamphetamine** [comment]
Oh, that would be too much.
