### ISSUE TITLE
Wrong parsing of number

### ISSUE THREAD

**Issue by NunoLopes12** [catamphetamine/libphonenumber-js#245]
I was trying to parse number with Belgium as country default code.
I got some wrong results using the parseNumber(value, 'BE').
For example value = 912123123.
When trying on the demo page https://catamphetamine.github.io/libphonenumber-js/ it works as expected.

I tried used the current, 1.4.4, version and an older one, 1.2.22, and still got the wrong results.

I am using this on a vuejs project.
Doing: import { parseNumber } from 'libphonenumber-js';

Am i doing something wrong?

**Comment by catamphetamine** [comment]
Post a pull request with a test case which you think behaves not as you expect.

**Comment by NunoLopes12** [comment]
I will do that asap.
In the meantime I made a fiddle that mimics the results I'm getting:
https://jsfiddle.net/NunoLopes/eywraw8t/343424/
Using the number: 931231231 i get a positive result on the fiddle but on the demo page it's a negative result.

Thanks for looking into it.

**Comment by catamphetamine** [comment]
The number is invalid
https://libphonenumber.appspot.com/phonenumberparser?number=931231231&country=BE

**Comment by catamphetamine** [comment]
“Fiddles” don’t matter, demo shows it’s invalid.

**Comment by NunoLopes12** [comment]
But then why is the function parseNumber extended turned true is returning the key valid as true?
Because that's my original question: getting a different result from the demo.
Sorry about the earlier fiddle it wasn't updated: https://jsfiddle.net/NunoLopes/eywraw8t/343939/
I will submit a test case later.
Again thanks for your time.

**Comment by catamphetamine** [comment]
Your fiddle shows that the number is valid.
The demo shows that it is invalid.
Update the library version in the fiddle and see if it fixes that.

**Comment by catamphetamine** [comment]
@NunoLopes12 
Actually, I checked and the number is valid.
So it is a valid number and your fiddle shows the expected result.
What's your issue?

![image](https://user-images.githubusercontent.com/477167/45222592-a5801d80-b2bd-11e8-9753-dea59f29d2d9.png)

**Comment by catamphetamine** [comment]
@NunoLopes12 
> I was trying to parse number with Belgium as country default code.
I got some wrong results using the parseNumber(value, 'BE').
For example value = 912123123.
When trying on the demo page https://catamphetamine.github.io/libphonenumber-js/ it works as expected.
I tried used the current, 1.4.4, version and an older one, 1.2.22, and still got the wrong results.

What exactly is the desired outcome and what is the observed outcome and what's the exact issue you're having.

**Comment by NunoLopes12** [comment]
@catamphetamine 
What I'm trying to do is: use parse phonenumbers with a Belgium as the default.
What I observed was a difference in the resulting outcome on the demo page and on my code.
I think that the demo page is parsing it correctly, but as you can see on the added image the same number that returned for you as valid returned for me, just now, as invalid.
I did test the numbers with the https://libphonenumber.appspot.com/ and keep gettign the same result as the demo page.

Finally: the version I am using is the 1.4.4 tag, tried also the 1.2.0 tag. On the fiddle its importing the 1.4.3 tag.

<img width="1198" alt="screen shot 2018-09-07 at 14 50 18" src="https://user-images.githubusercontent.com/20049035/45222836-75c91980-b2ad-11e8-94b9-f497ca567063.png">

I'm hoping my explanation isn't too confusing.

**Comment by catamphetamine** [comment]
> I'm hoping my explanation isn't too confusing.

I still don't understand.
Describe it in simple words:
* What is the behaviour you're experiencing
* What is the desired behaviour

**Comment by NunoLopes12** [comment]
- Experiencing: Getting invalid numbers returned as valid for Belgium. For example: 911231231
- Expected: Getting the invalid number as invalid, being consistent with the result of the demo page: https://catamphetamine.github.io/libphonenumber-js/ and the page: https://libphonenumber.appspot.com/

Maybe I should add that I'm working on a Mac. I'm not sure if that would trigger different results for the demo page.

**Comment by catamphetamine** [comment]
So, you're

* Expecting number `911231231` to be invalid for `BE`
* Experiencing it being valid

?

**Comment by NunoLopes12** [comment]
Exactly. 
Though that number is just an example, some other numbers starting with 9 + 8 numbers are also returning valid.

I noticed it by comparing with the results on the two test pages.

**Comment by catamphetamine** [comment]
Ok, I'll look into the issue.
Seems that Belgian numbers are either 8-digit ones or `4` + 8 digits for mobile numbers.
This one is 9 digits and doesn't start with `4`.

**Comment by NunoLopes12** [comment]
What made me raise the issue was the different results that I was getting.
Thanks for looking into it.

**Comment by NunoLopes12** [comment]
Thanks for the quick fix.
