### ISSUE TITLE
Lack of brackets in Russian locale

### ISSUE THREAD

**Issue by t1m0n** [catamphetamine/libphonenumber-js#246]
Hello, when formatting mobile phone number there are no brackets around operator neither country code before number in National format. But when using original library they are in place. I've attached screenshots to demonstrate what I mean:

### Google libphonenumber
![libphonenumber](https://user-images.githubusercontent.com/1918251/45412728-12a9ff00-b680-11e8-8486-3e26656a7770.png)

### libphonenumber-js
![libphonenumber-no-brackets](https://user-images.githubusercontent.com/1918251/45412776-30776400-b680-11e8-94fb-1cd73627d716.png)

Thank you.

**Comment by catamphetamine** [comment]
Released `libphonenumber-js@1.4.6` with the fix.

**Comment by t1m0n** [comment]
Wow fast! Thanks a lot!
