### ISSUE TITLE
Why is there no prebuilt minified version?

### ISSUE THREAD

**Issue by ppetree** [catamphetamine/libphonenumber-js#248]
I think the title says it all... all I want is a prebuilt minified version of the script where I can call the various functions.  I may or may not use all of the functionality but that's my choice.

Thanks,

P.

**Comment by catamphetamine** [comment]
Explain yourself in more detail.

**Comment by ppetree** [comment]
I'm not sure what else to say.  I want one .js file that contains all the functionality. I'll include that (originally in the header for testing but later on demand using $.getScript() for production).  

We don't use NPM. I can't copy all your files into a project.

**Comment by catamphetamine** [comment]
> We don't use NPM.

Then you should start using it.

Also you should start reading the descriptions of the libraries you're using in your projects.
