### ISSUE TITLE
Typescript type errors

### ISSUE THREAD

**Issue by asaarnak** [catamphetamine/libphonenumber-js#253]
TS1016: A required parameter cannot follow an optional parameter.
https://github.com/catamphetamine/libphonenumber-js/blob/6f2d21a81e0079e636c865f546bddeac5559c80e/custom.d.ts#L41
https://github.com/catamphetamine/libphonenumber-js/blob/6f2d21a81e0079e636c865f546bddeac5559c80e/custom.d.ts#L53

**Comment by catamphetamine** [comment]
@asaarnak 
Published `libphonenumber-js@1.5.1`.
I don't have TypeScript so I didn't test the fix.
Close if it's fixed.

**Comment by asaarnak** [comment]
Looks ok. Thanks!
