### ISSUE TITLE
getCountryCallingCode errors

### ISSUE THREAD

**Issue by virtualstyle** [catamphetamine/libphonenumber-js#258]
Using the library in React (import { getCountryCallingCode } from 'libphonenumber-js';).

Looping through a country list, appending the calling code to a select label with the country name. Pitcairn Islands (PN) call to getCountryCallingCode('PN'), kills the entire function: nothing further is processed after that statement fails, nothing gets reported in the console.

I'm gonna transfer my code to google-libphonenumber, so I'm not pushing you to resolve this, just thought you might want to know.

**Comment by catamphetamine** [comment]
Sumbit a test case if you think there might possibly be an issue.
Closing until then.
