### ISSUE TITLE
Different result

### ISSUE THREAD

**Issue by Fanda36** [catamphetamine/libphonenumber-js#260]
Hi,

I found different results for: https://libphonenumber.appspot.com/phonenumberparser?number=9042149505&country=CZ
There is "isValidNumber(): false" but in libphonenumber-js is result Parse (extended) - "valid: true" (on page https://catamphetamine.github.io/libphonenumber-js/ )
Do you have any idea how I can fix it?

Thank you.

**Comment by catamphetamine** [comment]
The demo uses the default metadata.
The default metadata doesn't contain validation regexps for most countries.
Use `metadata.full.json` for full validation regexps.
