### ISSUE TITLE
isValidNumber returns false for valid CN number

### ISSUE THREAD

**Issue by lz-lee** [catamphetamine/libphonenumber-js#263]
version：1.2.22
```
import metadata from './metadata.full.json';

let phone = new AsYouType();

phone.national_number = 1;
phone.country = 'CN';

var bool = isValidNumber(phone.national_number, phone.country || phone.metadata._country, metadata) 
```
and i got bool === false,

debug code find the function in Source code parse.js 

```
// The minimum length of the national significant number.
const MIN_LENGTH_FOR_NSN = 2

export function is_viable_phone_number(number)
{
	return number.length >= MIN_LENGTH_FOR_NSN &&
		VALID_PHONE_NUMBER_PATTERN.test(number)
}
```
when number is `1` ，`is_viable_phone_number`  return  false；
so why definition `MIN_LENGTH_FOR_NSN = 2` ？

**Comment by catamphetamine** [comment]
Yes, number `"1"` is not valid for any country because it's too short.

**Comment by catamphetamine** [comment]
`MIN_LENGTH_FOR_NSN = 2` is never used, yes, because `is_viable_phone_number` duplicates it.
Maybe I duplicated the check or something.
I'll see Google's code to check if they have the same duplication.
