### ISSUE TITLE
Angular Production error due to libphonenumber-js

### ISSUE THREAD

**Issue by cskasun** [catamphetamine/libphonenumber-js#264]
Hi,
I got 
`ERROR in node_modules/libphonenumber-js/index.d.ts(11,63): error TS1005: ',' expected.
node_modules/libphonenumber-js/index.d.ts(12,41): error TS1005: ';' expected.
node_modules/libphonenumber-js/index.d.ts(13,24): error TS1005: ';' expected.
node_modules/libphonenumber-js/index.d.ts(14,33): error TS1005: ';' expected.
node_modules/libphonenumber-js/index.d.ts(15,17): error TS1005: ';' expected.
node_modules/libphonenumber-js/index.d.ts(16,23): error TS1005: ';' expected.
node_modules/libphonenumber-js/index.d.ts(17,18): error TS1005: ';' expected.
`

when run ng serve

**Comment by catamphetamine** [comment]
Released `libphonenumber-js@1.6.1` with a fix.

**Comment by cskasun** [comment]
@catamphetamine Its is working. thank you
