### ISSUE TITLE
getType() dont work

### ISSUE THREAD

**Issue by romangua** [catamphetamine/libphonenumber-js#267]
![screen shot 2018-10-24 at 13 54 27](https://user-images.githubusercontent.com/13648024/47447634-5d955700-d794-11e8-9f04-65294c09a23b.png)

**Comment by catamphetamine** [comment]
It does work. Read the docs.

**Comment by catamphetamine** [comment]
I have updated the readme for `getType()`.
https://github.com/catamphetamine/libphonenumber-js#gettype
