### ISSUE TITLE
findNumbers: Two numbers separated by space - not working

### ISSUE THREAD

**Issue by supersnager** [catamphetamine/libphonenumber-js#268]
Please see following code:
`const txt = "513140867 513140868";
findNumbers(txt, 'PL', { v2: true });
`
function findNumbers returns array with one elment containing only first number.
Expected behaviour: return two elements with two numbers.

**Comment by catamphetamine** [comment]
Because that's how it works.
`"513140867 and 513140868"` finds both numbers.
`"513140867 513140868"` is not likely to be two phone numbers so it skips.

**Comment by supersnager** [comment]
Why  its not likely two numbers?

**Comment by catamphetamine** [comment]
Because it's more likely to be random numbers (not "phone numbers").

**Comment by catamphetamine** [comment]
Actually, the explanation is this: `findNumbers` is copy-pasted from Google's code:
https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberMatcher.java
So maybe their Java version doesn't parse your two numbers too.
And if that's the case then your question is for them.

**Comment by supersnager** [comment]
Thx :)
