### ISSUE TITLE
ambigous .getType() for same phones

### ISSUE THREAD

**Issue by vindi-r** [catamphetamine/libphonenumber-js#271]
Hello, I detect stange behavior for getType() function;

I use https://npm.runkit.com/libphonenumber-js for testing (1.6.4 lib version used)

with code: 
`var libphonenumberJs = require("libphonenumber-js")`
`console.log('plus: ' + libphonenumberJs.parsePhoneNumber('+79686509713').getType());`
`console.log('country: ' + libphonenumberJs.parsePhoneNumber('79686509713', 'RU').getType());`

In result i see this:

`"plus: MOBILE"`
`"country: undefined"`

Please explain me, this is bug or feature.

Regards, Mikhail.

**Comment by catamphetamine** [comment]
`79686509713` is not a valid number.

**Comment by catamphetamine** [comment]
`79686509713` is not a valid number.
Google corrects your error.
`+79686509713` is the valid number.

**Comment by vindi-r** [comment]
But why google lib recognize my number when i specify "default country" param, and this library does not?

I thought that default country param helps determine phone if it written not in e164 format.

**Comment by catamphetamine** [comment]
@vindi-r Because google's library is more forgiving to wrong input in this case.
