### ISSUE TITLE
Invalid parsing phone numbers

### ISSUE THREAD

**Issue by denis-n** [catamphetamine/libphonenumber-js#273]
Hello,

I'm new to this library, started to use it yesterday.

For these phone numbers the demo page shows that they are valid:

https://libphonenumber.appspot.com/phonenumberparser?number=85264522489&country=HK
https://libphonenumber.appspot.com/phonenumberparser?number=441206700399&country=GB

But this code shows that they are not valid:
```
    console.log(
      true === parsePhoneNumber('85264522489', 'HK', metadata).isValid(),
    );

    console.log(
      true === parsePhoneNumber('441206700399', 'GB', metadata).isValid(),
    );
```

I'm using just generated metadata, version **1.6.5**

Same numbers are valid when they have '+' at beginning:
```
+85264522489
+441206700399
```

**Comment by catamphetamine** [comment]
Yes, because neither `85264522489` nor `441206700399` are valid numbers: they must be preceded by a `+`.
