### ISSUE TITLE
integration in a Thunderbird addon

### ISSUE THREAD

**Issue by CardBook** [catamphetamine/libphonenumber-js#277]
Hi Nikolaї

Sorry to create an issue for this but I haven't found an email to join you... so I'm Philippe Vigneau, the CardBook (https://addons.thunderbird.net/ru/thunderbird/addon/cardbook/) developer, and I'd like to integrate your library into CardBook, have you got a tuto on how to do ?

Philippe

**Comment by catamphetamine** [comment]
I suggest you follow the readme and use the `libphonenumber-js/max` subpackage to import functions.
In case of difficulties post here.
