### ISSUE TITLE
missing typescript definition for AsYouType custom

### ISSUE THREAD

**Issue by aitboudad** [catamphetamine/libphonenumber-js#278]
the following import throw `Module '/node_modules/libphonenumber-js/custom"' has no exported member 'AsYouType'.` error

```ts
import { AsYouType } from 'libphonenumber-js/custom';
```

**Comment by catamphetamine** [comment]
Fixed in `libphonenumber-js@1.6.8`.

**Comment by aitboudad** [comment]
Thanks!
