### ISSUE TITLE
8 digit phone numbers in india are valid

### ISSUE THREAD

**Issue by mderazon** [catamphetamine/libphonenumber-js#280]
Number:
> +9112345678

Libphonenumber says it's invalid and libphonenumber-js says it's valid
https://libphonenumber.appspot.com/phonenumberparser?number=%2B9112345678&country=91

**Comment by catamphetamine** [comment]
Test with full metadata.
If with full metadata it won't work then submit a unit-test or a sample project illustrating the issue.
