### ISSUE TITLE
Get metadata

### ISSUE THREAD

**Issue by sm2017** [catamphetamine/libphonenumber-js#285]
How can I get metadata? 
I want to get list of available country codes

**Comment by catamphetamine** [comment]
```js
import { Metadata } from 'libphonenumber-js/core'
import metadata from 'libphonenumber-js/metadata.min.json'
new Metadata(metadata).countryCallingCodes()
```

**Comment by AleRob90** [comment]
Hello, the Metadata became a type meanwhile.
I have tried the above code, but i get an error, 'Metadata' only refers to a type, but is being used as a value here.

**Comment by catamphetamine** [comment]
> Hello, the Metadata became a type meanwhile.
> I have tried the above code, but i get an error, 'Metadata' only refers to a type, but is being used as a value here.

Hello.
I'm not familiar with TypeScript.
If you think there's a bug then you can post the exact error message and such.

**Comment by say8425** [comment]
I agree. Metadata looks something [weird](https://github.com/catamphetamine/libphonenumber-js/blob/master/core/index.d.ts#L2). 
Anyway, you can get all countryCodes using metadata.

```typescript
import metadata from 'libphonenumber-js/metadata.min.json'

Object.keys(metadata.countries);
```

**Comment by catamphetamine** [comment]
The list of available countries could be get via `getCountries()`.
https://github.com/catamphetamine/libphonenumber-js#getcountries-string

The exported `Metadata` name is already used for exporting the "raw" JSON metadata type.
Then, `Metadata` class has become exported, but its name is already taken, so TypeScript users seem to be unable to use the `Metadata` class.
If someone knows a solution then they could propose it in an issue.

**Comment by say8425** [comment]
```typescript
import { getCountries } from 'libphonenumber-js'

getCountries();
```

It works perfectly! Thanks 🤩
