### ISSUE TITLE
TS Compilation Error: An import path cannot end with a '.d.ts' extension.

### ISSUE THREAD

**Issue by juliusstoerrle** [catamphetamine/libphonenumber-js#292]
Hi, in my Angular 7 project I updated this lib to 1.7.6 today. Now I recieve following error:

> ERROR in node_modules/libphonenumber-js/index.d.ts(17,8): error TS2691: An import path cannot end with a '.d.ts' extension. Consider importing './types' instead.

When appling the recommended fix, everything works.

Typescript: 3.2.2

**Comment by catamphetamine** [comment]
Ok, released `libphonenumber-js@1.7.7` with the fix.
