### ISSUE TITLE
New format

### ISSUE THREAD

**Issue by Ricki-BumbleDev** [catamphetamine/libphonenumber-js#295]
In Germany the following phone number format is very common: `+49 (0)40 1234567`. This combines the national and international format. If the national format is used, the `+49` is skipped and the zero must be used. If the international format is used, the `+49` is entered and the zero is skipped, which is why the zero is printed in brackets.

Would be cool to have a formatter for this format or to be able to pass a custom formatter function into the format function, that gets called with the different parts of the phone number, that could then be assembled as wished.

**Comment by catamphetamine** [comment]
Not gonna happen. Such phone number format is invalid.

**Comment by Ricki-BumbleDev** [comment]
Thanks for your quick response! Whether or not the format is invalid is arguable. Anyways, it doesn't make the format less common. I can understand that any "special" formats shouldn't be added for everyone, however, being able to pass a custom formatter function for such cases would be nice, wouldn't it?

**Comment by catamphetamine** [comment]
I think it’s better for this library to mimick Google’s API and not extend
it with extra features which increase msintenance complexity.
