### ISSUE TITLE
AsYouType not formatting Australian 6-digit numbers w/ leading 13 properly

### ISSUE THREAD

**Issue by henser** [catamphetamine/libphonenumber-js#297]
AsYouType doesn't seem to be formatting Australian "6-digit variable cost fixed line (toll free, premium rate, shared cost)" with leading '13' phone numbers properly. These are being identified as SHARED_COST and are correctly described in the metadata xml and as far as I know they were working properly before.

This is the xml descriptor:

        
        <numberFormat pattern="(\d{2})(\d{2})(\d{2})">
          <leadingDigits>13</leadingDigits>
          <format>$1 $2 $3</format>
          <intlFormat>NA</intlFormat>
        </numberFormat>

And here's an example in action showing format 13xxxx instead of expected 13 xx xx.

![screen shot 2019-02-07 at 11 02 17 am](https://user-images.githubusercontent.com/1830426/52383166-183d3100-2ac8-11e9-8f97-a5f8b509af25.png)

**Comment by catamphetamine** [comment]
The reason is that the number you're formatting is a "short code" which aren't formatted by this library.

See the "Differences" section:
https://github.com/catamphetamine/libphonenumber-js#difference-from-googles-libphonenumber

```xml
        <!-- Premium rate SMS (6 digit) -->
        <numberFormat pattern="(\d{3})(\d{3})">
          <leadingDigits>19</leadingDigits>
          <format>$1 $2</format>
          <intlFormat>NA</intlFormat>
        </numberFormat>
```
