### ISSUE TITLE
Does not parse GB properly without +

### ISSUE THREAD

**Issue by rtaft** [catamphetamine/libphonenumber-js#298]
Using the input '441843297700' and the default country US, it fails to ID this as UK and flags it as invalid.
Setting the country to GB also flags it as invalid and appends +44 to the front.  This only works properly if there is a + in the front, which my data source does not have.

**Comment by catamphetamine** [comment]
> which my data source does not have.

Your data source is invalid.

**Comment by rtaft** [comment]
Setting the country code to GB should handle it properly, Googles version does.  This appends an extra +44 to it.  The data source is a number, not a string...like a real phone.

**Comment by catamphetamine** [comment]
> This appends an extra +44 to it.

Valid local numbers are parsed correctly.
You're talking about invalid numbers.
