### ISSUE TITLE
Finding out country code

### ISSUE THREAD

**Issue by latusdenis** [catamphetamine/libphonenumber-js#299]
Using libphonenumber-js with ReactNative. In the phone memory, I have contacts like 51616777, etc. Is it possible to find what's the country code, depending on the number using libphonenumber-js methods? I need to pass dynamic parameter instead of RU, depending on the number.

```
   let phoneNumberParsed = parsePhoneNumberFromString(contact.phoneNumbers[0].number, 'RU');
```

Thanks!

**Comment by catamphetamine** [comment]
Only `+` numbers can be parsed without a country.

**Comment by latusdenis** [comment]
> Only `+` numbers can be parsed without a country.

Do you mean, that the numbers can be parsed only with country code?

**Comment by catamphetamine** [comment]
I meant that if you're passing a number to the parse function then it either must start with `+` or you must supply a country code.

**Comment by latusdenis** [comment]
> I meant that if you're passing a number to the parse function then it either must start with `+` or you must supply a country code.

Got it. And as I understand there's no opportunity to calculate the country code depending on the number without it in the lib?

**Comment by catamphetamine** [comment]
Without `+` there's no country info.
