### ISSUE TITLE
US phone not recognized

### ISSUE THREAD

**Issue by arnaudambro** [catamphetamine/libphonenumber-js#301]
Hi there,

I try to validate "Anna Haro"'s phone number, one of the fake default contacts of iOS Simulator, it doesn't work, do you know why ?

Try this : 
```js
const num = parsePhoneNumberFromString('+15555228243');
console.log('parsePhoneNumberFromString', num, num.isValid());
```

**Comment by VladimirDev93** [comment]
@arnaudambro You didn't add the country code, `US`

```js
const num = parsePhoneNumberFromString('+15555228243', 'US');
```

**Comment by arnaudambro** [comment]
@VladimirDev93 still not working for me, with or without the country code. is it really working for you ?

**Comment by VladimirDev93** [comment]
@arnaudambro Yes. Here is the code example from my code

```js
import { parsePhoneNumberFromString } from 'libphonenumber-js';

// Parse the phone number
const phoneNumber = parsePhoneNumberFromString(number, 'RS');
if (phoneNumber) {
    console.log(phoneNumber);
}
```
***number*** is string

**Comment by arnaudambro** [comment]
Yeah, but what I want is `isValid` to work. Or maybe "+15555228243" is truly a non valid number, but I am not american so I am not sure...

**Comment by catamphetamine** [comment]
@arnaudambro 
> Or maybe "+15555228243" is truly a non valid number, but I am not american so I am not sure...

You can check that on Google's demo page (see the readme).
Also see the notes in the readme about min vs max metadata.
If you find out that Google's demo works and max metadata doesn't then reopen this issue.
