### ISSUE TITLE
Issue with validating Serbian numbers

### ISSUE THREAD

**Issue by nikola993** [catamphetamine/libphonenumber-js#303]
I am validating phone numbers with isValid() in node backend and react front end. For some numbers, I got return true on the frontend and false on the backend. For example when I am using +381123123123 node return false and react return true

**Comment by catamphetamine** [comment]
It's most likely that you're using different metadata in browser and in Node.
You can check which `index.common.js` file does the Node import from and then you can see which version of metadata does that index file import.

**Comment by nikola993** [comment]
In both versions, I import metadata.min.json for metadata. Any other things I should check?

**Comment by catamphetamine** [comment]
No other suggestions

**Comment by nikola993** [comment]
Ok, I fixed it with importing libphonenumber-js/mobile in my react app.
