### ISSUE TITLE
parsePhoneNumberFromString() returns undefined with "+0" number prefix.

### ISSUE THREAD

**Issue by tohagan** [catamphetamine/libphonenumber-js#307]
Calling `parsePhoneNumberFromString("+0407123456", "AU")`  returns the value `undefined`.

This is caused by extractCountryCallingCode() on parse_.js line 

```
// Fast abortion: country codes do not begin with a '0'
if (number[1] === '0')
{
	return {}  // returns by extractCountryCallingCode()
}
```

```
let { countryCallingCode, number } = extractCountryCallingCode(formatted_phone_number, default_country, metadata.metadata)
```

So  `countryCallingCode` and `number`  are now both undefined.

**Comment by catamphetamine** [comment]
This is correct because country calling code can't start with a zero.
And Australian code is `+61`.

**Comment by tohagan** [comment]
This is a BUG because `parsePhoneNumberFromString("+0407123456", "AU").isValid()` crashes because `parsePhoneNumberFromString("+0407123456", "AU")` is undefined

**Comment by catamphetamine** [comment]
@tohagan If you read the README more thoroughly you'd know that it is supposed to be this way.
https://github.com/catamphetamine/libphonenumber-js#parsephonenumberfromstringstring-defaultcountry

**Comment by tohagan** [comment]
Ok that's a weird API interface but I can hack around it. Thanks.

**Comment by catamphetamine** [comment]
No, that's a perfectly correct API interface and only weird code needs to hack around that.

**Comment by ajsultandev** [comment]
Instead of returning undefined, it might be better to just return a blank PhoneNumber instance with isValid set to false. That's why there is an isValid function for PhoneNumber, to return if the number given is valid or not. This situation falls under that.
