### ISSUE TITLE
parsePhoneNumberFromString("+0407123456", "AU").isValid() throws exception

### ISSUE THREAD

**Issue by tohagan** [catamphetamine/libphonenumber-js#309]
This is a BUG because `parsePhoneNumberFromString("+0407123456", "AU").isValid()` crashes because `parsePhoneNumberFromString("+0407123456", "AU")` is undefined

**Comment by catamphetamine** [comment]
@tohagan If you read the README more thoroughly you'd know that it is supposed to be this way.
https://github.com/catamphetamine/libphonenumber-js#parsephonenumberfromstringstring-defaultcountry
It clearly states that it will return `undefined` if the number is not a valid one.
