### ISSUE TITLE
Wrong UA (Ukraine) number validation

### ISSUE THREAD

**Issue by egnashko** [catamphetamine/libphonenumber-js#312]
Hi!
Find an issue with UA (Ukraine) phone numbers.
The correct format for mobile phone numbers is +380 XXX XX XX.

For example number is +3800671234567 validating pass (true). But it is incorrect, number must be +380671234567.
Investigate that it works only with 0 before number and all other numbers validate correctly.
correct (validating correct)
```
+380671234567
Possible: true
Valid: true
```
correct (validating incorrect)
```
+3800671234567
Possible: true
Valid: true
```
incorrect (validating correct)
```
+3801671234567
Possible: true
Valid: true
```

**Comment by catamphetamine** [comment]
See the Bug Reporting section of the readme.
