### ISSUE TITLE
French mobile phone starting with 07 are considered as incorrect

### ISSUE THREAD

**Issue by EikiProg** [catamphetamine/libphonenumber-js#314]
Since 3 may 2010, french mobile phone starting with 07 are correct mobile phone number.

https://libphonenumber.appspot.com/phonenumberparser?number=0716693321&country=FR&geocodingLocale=fr-FR

**Comment by catamphetamine** [comment]
The Google demo says the number is not valid.

**Comment by catamphetamine** [comment]
You should report it to Google then.
This library uses Google's metadata.

**Comment by EikiProg** [comment]
Well i can't post an issue on https://github.com/googlei18n/libphonenumber, too bad they are 9 year late.

**Comment by catamphetamine** [comment]
They accept issues via Google Groups or something.
Read ther FAQ or README, it was there somewhere.

**Comment by jdequeant** [comment]
Can you reopen this issue ? Google accepts now mobile phone number starting with 07 (https://libphonenumber.appspot.com/phonenumberparser?number=0780808080&country=FR) but not this library.

**Comment by catamphetamine** [comment]
Provide the full info: what exactly you think is different between this library demo and google's demo.

**Comment by jdequeant** [comment]
Sorry, I've tried two different numbers (0780808080 and 0714481221). Indeed, both libraries considers that the first number is valid but not the second one. Sorry for the inconvenience.

**Comment by aminesafi8** [comment]
Any news?
