### ISSUE TITLE
Semver-compare does not exist the haste module map with React Native

### ISSUE THREAD

**Issue by mdere-unbound** [catamphetamine/libphonenumber-js#320]
So I looked in this ticket https://github.com/catamphetamine/libphonenumber-js/issues/239 - but wasn't sure if it applied to this

![image](https://user-images.githubusercontent.com/46753241/58763525-ba769e00-8529-11e9-8348-37c82f38cc53.png)

I am currently on the latest libphone and on react native 0.58.4 and React 16.6.3

Let me know if you need any more information.

**Comment by catamphetamine** [comment]
You could try reinstalling your `node_modules` because `semver-compare` is not imported anywhere in the latest version.

**Comment by catamphetamine** [comment]
Seems that no one's having the issue so far except the OP.
Closing for now.
