### ISSUE TITLE
Incorrect 001 region parse/format

### ISSUE THREAD

**Issue by vegarda** [catamphetamine/libphonenumber-js#323]
Please see the image below -- is this correct?

![image](https://user-images.githubusercontent.com/2388995/59411232-0abbee80-8dbb-11e9-8a16-00dc9a8494eb.png)

**Comment by catamphetamine** [comment]
What does the Google's demo say in this case?

**Comment by vegarda** [comment]
+870773111632
https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

`****Parsing Result:****
{"country_code":870,"national_number":773111632,"raw_input":"+870773111632","country_code_source":1}

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): true
Phone Number region: 001
Result from getNumberType(): MOBILE

****Formatting Results:**** 
E164 format: +870773111632
Original format: +870 773 111 632
National format: 773 111 632
International format: +870 773 111 632
Out-of-country format from US: 011 870 773 111 632
Out-of-country format from Switzerland: 00 870 773 111 632`

**Comment by catamphetamine** [comment]
Seems like a bug to me, but currently I'm having busy days and there're a couple of other things in `libphonenumber-js` I haven't done yet (like merging some of Google's commits during this/past year).
I guess this will be fixed in future when I have enough free time.

**Comment by vegarda** [comment]
@catamphetamine have you had some time to look at this?

**Comment by catamphetamine** [comment]
@vegarda You can laugh but no I haven't.
For some reason, I've been busy for this half of year, and I don't see how I'm free in the near future.
However, some day I will look into it and fix it.

**Comment by catamphetamine** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/477167/73707874-cb595e00-470d-11ea-9768-e4c847a04e3d.png)
