### ISSUE TITLE
Valid US phone number failing validation

### ISSUE THREAD

**Issue by horaciooktana** [catamphetamine/libphonenumber-js#327]
I have an issue trying to validate a valid US number: +14086953523‬
The google demo page says its a valid number, but when i check here i get the error NOT_A_NUMBER.
Is there something i can do on my end to fix this? Can you confirm this fails for you too?
Any help is really appreciated!

**Comment by catamphetamine** [comment]
The demo works.
See the screenshot.

![image](https://user-images.githubusercontent.com/477167/60214886-20c3b780-986f-11e9-98da-4167dbedde87.png)
