### ISSUE TITLE
Country Code IN - Incorrect Phone Number validation

### ISSUE THREAD

**Issue by sibiraj-sr** [catamphetamine/libphonenumber-js#328]
```
var ljs = require("libphonenumber-js")

console.log(ljs.parsePhoneNumberFromString('+9112345678').isValid()) // returns true
```

In the above code, the given Indian phone number is invalid. phone numbers must have 10 digits excluding country code.

JFR: https://libphonenumber.appspot.com/phonenumberparser?number=%2B9112345678

**Comment by catamphetamine** [comment]
The demo works, you're using non-max metadata.

**Comment by sibiraj-sr** [comment]
Thanks. using `var ljs = require("libphonenumber-js/max")` works.
