### ISSUE TITLE
Unable to do customise mobile library like min.meta.json functionality

### ISSUE THREAD

**Issue by priyankapyt** [catamphetamine/libphonenumber-js#329]
Unable to do customise mobile library like min functionality.

I want to remove mobile.meta.json from my code for that I tried custom format as mentioned in the documentation but after that parsePhoneNumberFromString of mobile lib is not working.

**Comment by catamphetamine** [comment]
It's not clear what you mean at all

**Comment by priyankapyt** [comment]
Sorry if I was not clear enough.
Actually in my current app I'm using libphonenumber-js/mobile. 
But for optimisation i want to remove the meta.mobile.json out of my bundle. 

So i was trying script to create custom meta file and use it.

But it is not working as expected for parsePhoneNumberFromString function from mobile version of it.

**Comment by catamphetamine** [comment]
> But for optimisation i want to remove the meta.mobile.json out of my bundle.

The library requires some metadata to work with.
Otherwise it won't work.

**Comment by priyankapyt** [comment]
Yes, that meta data file i'm passing as a parameter exactly as it is mentioned in custom meta-data part of documentation.

But that is working for functions from min version of library not from mobile part of it.

**Comment by catamphetamine** [comment]
> It is working as expected for functions from min flavor of library not for functions from mobile flavor of it.

Don't use `min` or `mobile` in that case, use `custom`.

**Comment by priyankapyt** [comment]
Yes, I'm using custom flavor. But in that if you use below function it gives true and in mobile flavor it gives false.

parsePhoneNumberFromString('+911234567890').isValid()

Here 1234567890 is wrong mobile number entered by user.

**Comment by catamphetamine** [comment]
If the results aren't valid then perhaps the metadata isn't valid.

Post how you generate your metadata.

**Comment by priyankapyt** [comment]
"libphonenumber-metadata": "libphonenumber-generate-metadata metadata.min.json",

**Comment by catamphetamine** [comment]
There's no need to do that — it won't differ from the `min` metadata.

**Comment by priyankapyt** [comment]
correct, so in a nutshell -> I have just kept the meta files out of the bundle and using custom flavour by passing metaData as parameter.

But in that case  below function gives true and when I use mobile flavor it gives false. (expectesd result is false as 1234567890 is invalid no)

parsePhoneNumberFromString('+911234567890').isValid()

**here 1234567890 is wrong mobile number entered by user.

**Comment by priyankapyt** [comment]
Closing the issue, got it. I was not passing the correct meta data files. Thanks @catamphetamine 
 for directing towards  correct issue.
