### ISSUE TITLE
Missing Country Code - US Minor Outlying Islands

### ISSUE THREAD

**Issue by shmolf** [catamphetamine/libphonenumber-js#330]
I'm getting an issue when referencing a couple of different county codes.

- [ ] `UM` [United States Minor Outlying Islands](https://www.iso.org/obp/ui/#iso:code:3166:UM)
- [ ] `GS`  [South Georgia and the South Sandwich Islands](https://www.iso.org/obp/ui/#iso:code:3166:GS)
- [ ] `PN` [Pitcairn](https://www.iso.org/obp/ui/#iso:code:3166:PN)

There may be a few more. I haven't checked them all.

I looked in [This File](https://github.com/catamphetamine/libphonenumber-js/blob/master/test/metadata/1.1.11/metadata.full.json), but did not see a reference.

**Comment by catamphetamine** [comment]
See if those are available in Google's demo.
If they aren't then this issue will be closed.

**Comment by shmolf** [comment]
@catamphetamine Could not see in the [Google metadata](https://github.com/google/libphonenumber/blob/e5daf21fb1ebcc522a987ce00b44889100a8013b/javascript/i18n/phonenumbers/metadata.js)

As an cross-check, Pitcairn is listed under the New Zealand CC.
This might be an issue that belongs on that project, then.

TY

**Comment by catamphetamine** [comment]
> This might be an issue that belongs on that project, then.

Yeah, they have "Google Groups" for issues (or something like that).
This project just re-uses Google's metadata providing a more convenient API.
