### ISSUE TITLE
Version 1.7.21 removed 11 digits italian phone numbers

### ISSUE THREAD

**Issue by asmeikal** [catamphetamine/libphonenumber-js#333]
https://github.com/catamphetamine/libphonenumber-js/commit/7c4e4cd78daf90016ed9c58551d0c5b9b5de953f#diff-be77ab173a119f6e59b5a193ee1841c2R14027

The comments says that 11 digits number exist in Italy, but "+39 333 33 33 3333" is not valid.

**Comment by catamphetamine** [comment]
Hello.
This library only copies metadata from Google's library:
https://github.com/google/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml
If you think there's something with the metadata then report it to google in their google groups.
