### ISSUE TITLE
formatPhoneNumber doesn't format properly

### ISSUE THREAD

**Issue by LitvinenkoEvgeny** [catamphetamine/libphonenumber-js#337]
https://libphonenumber.appspot.com/phonenumberparser?number=89020423527&country=RU

```javascript
const { formatPhoneNumber, formatPhoneNumberIntl } = require('react-phone-number-input/max');

const value = '89020423527';
console.log(formatPhoneNumber(value)); // in fact - returns empty string
console.log(formatPhoneNumberIntl(value)); // same here

```
 "react-phone-number-input": "2.3.21"
"libphonenumber-js": "^1.7.22",

What i'm doing wrong ?

**Comment by catamphetamine** [comment]
Provide a demo somewhere on codesandbox

**Comment by LitvinenkoEvgeny** [comment]
@catamphetamine 
https://codesandbox.io/s/intelligent-pascal-wpkz3
