### ISSUE TITLE
formatPhoneNumber doesn't format properly

### ISSUE THREAD

**Issue by LitvinenkoEvgeny** [catamphetamine/libphonenumber-js#338]
https://libphonenumber.appspot.com/phonenumberparser?number=89020423527&country=RU

```javascript

const { formatPhoneNumber, formatPhoneNumberIntl } = require('react-phone-number-input/max');

const value = '89020423527';
console.log(formatPhoneNumber(value)); // in fact - returns empty string
console.log(formatPhoneNumberIntl(value)); // same here
```

demo: https://codesandbox.io/s/intelligent-pascal-wpkz3

**Comment by catamphetamine** [comment]
Go to the readme and search for `formatPhoneNumber` — there's no such function anymore.
Instead use `parsePhoneNumberFromString().format(...)`.

**Comment by LitvinenkoEvgeny** [comment]
@catamphetamine 
https://github.com/catamphetamine/react-phone-number-input#use

**Comment by catamphetamine** [comment]
You're looking at the incorrect link.
Look at this repo readme

**Comment by LitvinenkoEvgeny** [comment]
yes but i'm don't use this lib directly, and why react-phone-number-input does not encapsulate it?

**Comment by catamphetamine** [comment]
It's not clear what you mean and what you want
