### ISSUE TITLE
Why does versioning differ from NPM?

### ISSUE THREAD

**Issue by simplenotezy** [catamphetamine/libphonenumber-js#340]
If I take a look at: https://www.npmjs.com/package/libphonenumber-js versioning differs. It seems as the same library though.

I am switching form NPM to Bower in a web-project, and this is how I noticed the version change.

We was using: `1.7.21` but it seems as though we need to use `0.2.2` instead?

**Comment by catamphetamine** [comment]
Not clear what you mean.
The link to `npm` is correct.

**Comment by simplenotezy** [comment]
On NPM:

![image](https://user-images.githubusercontent.com/3786627/65072041-58cf2800-d990-11e9-88db-c9a4fc8f7fdd.png)


On GitHub:
![image](https://user-images.githubusercontent.com/3786627/65072064-6be1f800-d990-11e9-8410-66b3616a5a3f.png)

**Comment by catamphetamine** [comment]
Oh, I see.
These "releases" seem to be accidental.
Ignore them.

**Comment by catamphetamine** [comment]
There seems to be no way to delete them.
