### ISSUE TITLE
Should contain a minified release

### ISSUE THREAD

**Issue by simplenotezy** [catamphetamine/libphonenumber-js#341]
As I merge in scripts from my /bower_components/ I would expect a minified file of the distribution. Currently I find no `lib-phonenumber.js` or `lib-phonenumber.min.js`, so I am unsure how to pull it in.

**Comment by catamphetamine** [comment]
See the `bundle` folder of the npm package.

**Comment by simplenotezy** [comment]
Could we include this in the bower release as well?

**Comment by catamphetamine** [comment]
Well, I didn't use bower and if there's something in it then it wasn't me.
