### ISSUE TITLE
How do I get region code from a number?

### ISSUE THREAD

**Issue by simplenotezy** [catamphetamine/libphonenumber-js#342]
I'd like to get the region code for a specific number, however, I'm having troubles figuring out how the library works.

So far I have tried this:

    import {isPossibleNumber, parsePhoneNumberFromString} from 'libphonenumber-js';
    parsePhoneNumberFromString(input.val()).getRegionCodeForNumber();

That does not work however.

**Comment by catamphetamine** [comment]
There's no such function.
See the readme on how to do that.

**Comment by simplenotezy** [comment]
I believe such a function definitely exists:

    parsePhoneNumberFromString(input.val()).country;

**Comment by simplenotezy** [comment]
Thanks anyway
