### ISSUE TITLE
bundle size optimization strategies

### ISSUE THREAD

**Issue by ganqqwerty** [catamphetamine/libphonenumber-js#344]
How can I reduce the size of the bundle for libphonenumber.js? 
We only use the following functions from the library in our Angular project: 
```
import { CountryCode, AsYouType, format, isValidNumber, parse } from 'libphonenumber-js';
```
Yet, the resulting size of the libphonenumber in our bundle is 300Kb uncompressed, that's quite a lot, IMO. Is there any room for the optimisation and tree shaking? 

![image](https://user-images.githubusercontent.com/697308/65410949-e628d700-ddeb-11e9-93ba-60573c5ad39a.png)

**Comment by catamphetamine** [comment]
You should investigate which files take up the space.
Reopen if needed.
