### ISSUE TITLE
Can't module import

### ISSUE THREAD

**Issue by jatbone** [catamphetamine/libphonenumber-js#350]
Hi,
it isn't possible to import only one desired functionality.

Would be nice to import just one function like this:
`import parsePhoneNumber from 'libphonenumber-js/es6/parsePhoneNumber'`

Thanks

**Comment by catamphetamine** [comment]
Well, maybe.
For ES6 you could try something like:

```js
import parsePhoneNumber from 'libphonenumber-js/modules/parsePhoneNumber'
```

Look at the `node_modules/libphonenumber-js` folder contents to see the available import paths.

**Comment by hukus** [comment]
Tried all possible combinations - none of them work. Not even tree shaking works on this lib. It is always takes huge part of bundle size because it is loaded over and over in each form... I wonder how can we import it only once and then serve the `parse` functionality to the rest of the codebase. Any ideas?

Thanks <3

**Comment by catamphetamine** [comment]
@hukus 

> Not even tree shaking works on this lib. It is always takes huge part of bundle size because it is loaded over and over in each form.

If you're claiming something then provide a proof.

**Comment by hukus** [comment]
![libphonejs](https://user-images.githubusercontent.com/16256404/69252843-f115a300-0bb3-11ea-836f-b921894a0e2e.png)
Sorry, didn't mean to sound offensive :)

We just use `parse` function in three different places and it imports a huge chunks every time. Tree shaking works for other packages in our project. Any ideas what to do?

**Comment by catamphetamine** [comment]
> Sorry, didn't mean to sound offensive

That wasn't offensive.

The screenshot you provided is blurred.

**Comment by catamphetamine** [comment]
If your application has several chunks then the library will be part of every chunk unless you explicitly tell Webpack to "extract commons" somehow.
There was "extract commons" plugin before, in old versions.
This is not an issue of this library.

**Comment by hukus** [comment]
Blurred beause I don't think I can publicly show details of our project. 
As for webpack, we don't use it, we rely on Nextjs tree shaking. I will go check if nextjs has the `extract commons` feature or something, thanks!

**Comment by catamphetamine** [comment]
> Blurred beause I don't think I can publicly show details of our project.

As if anyone cares about your project.
