### ISSUE TITLE
Uncaught Error: Unknown country: BV

### ISSUE THREAD

**Issue by wmtamit** [catamphetamine/libphonenumber-js#351]
-> When I come back after some days then I run code then give me an error. I know this is error generate because of country no present. but before someday this work and suddenly this gives the error
Please Help 

code link :-> https://jsfiddle.net/de5uswcz/

**Comment by catamphetamine** [comment]
There's no `BV` country in `libphonenumber`.
See the available countries list:
https://unpkg.com/browse/libphonenumber-js@1.7.26/metadata.min.json

**Comment by catamphetamine** [comment]
`libphonenumber-js@1.7.27`

1.7.27 / 18.11.2019
===================

  * Added `getCountries()` function that returns a list of all available two-letter country codes. This is to prevent some users from having to deal with `Unknown country` error.

**Comment by yinguangyao** [comment]
@catamphetamine Uncaught Error: Unknown country: AQ
