### ISSUE TITLE
import from unpkg.com generated file

### ISSUE THREAD

**Issue by jochenrick** [catamphetamine/libphonenumber-js#362]
I generated a libphonenumber.js package from unpkg.com (1.7.6, min) and have been trying to use it in an ES6 module. I can't seem to get the import working. I try to do the following in my ES6 module:
`import {AsYouType, parsePhoneNumberFromString} from './libphonenumber-min.js';`
I then get this in the browser console:
`Uncaught SyntaxError: The requested module './libphonenumber-min.js' does not provide an export named 'AsYouType'`
I've also tried doing the following but the same thing:
`import {libphonenumber} from './libphonenumber-min.js';`

**Comment by catamphetamine** [comment]
If you're using the CDN version then see the CDN section of the readme.
If you're using ES module imports then import from the root folder of the module, not the files from the `build` folder.
