### ISSUE TITLE
How to add newly added prefix

### ISSUE THREAD

**Issue by chz** [catamphetamine/libphonenumber-js#363]
How to add newly added prefix?

+994 99 8998855

**Comment by chz** [comment]
is it possible via configs or?

**Comment by catamphetamine** [comment]
To add new prefixes contact Google.
This library uses their metadata.
https://github.com/google/libphonenumber

**Comment by chz** [comment]
Can i add manually ? if yes how ? I need this.

**Comment by chz** [comment]
@catamphetamine http://libphonenumber.appspot.com/phonenumberparser?number=%2B994998998855&country=AZ&geocodingLocale=az-AZ 

They are added i think how i can fix it?

**Comment by catamphetamine** [comment]
It's not clear what exactly you want.
If you think there's a bug then see the "Bug reporting" section of the readme.
Otherwise, contact Google.
