### ISSUE TITLE
Problem deleting number with AsYouType 

### ISSUE THREAD

**Issue by VisheshSingh** [catamphetamine/libphonenumber-js#364]
I am using AsYouType to format the number which seems to be working perfectly fine. However, when I try the deleting the number it just stops me at the ")". The demo provided seems to be working fine as it jumps over the ")" when you try deleting the number.

Here's a code sandbox - https://codesandbox.io/s/romantic-dawn-1tuce

Let me know if i am missing anything here?

**Comment by catamphetamine** [comment]
https://github.com/catamphetamine/libphonenumber-js/issues/225
