### ISSUE TITLE
Default country US returns other NANP numbers as invalid

### ISSUE THREAD

**Issue by joallard** [catamphetamine/libphonenumber-js#368]
Entering a NANP country (US) as a default country, and entering a NANP number from another country, the library will return the number as invalid.

On [the demo](https://catamphetamine.github.io/libphonenumber-js/), section *As you type*:

1. Enter 'US' as default country
2. Enter '514 555-1212' as number

=> `valid: false`

I know the `valid` field is limited, but that seems kind of a stretch. Besides, "default country" doesn't mean "exactly this country".

**Comment by catamphetamine** [comment]
`valid` means “valid for the country specified”.

**Comment by catamphetamine** [comment]
If you want NANPA validation then pass international numbers instead, by prepending `+1` in case of NANPA.

**Comment by joallard** [comment]
Thank you for your response. The UX issue has since stopped existing, as users realized they were wrong. I will add a tooltip "Dear human, please take a few seconds of your existence to change the country in the dropdown menu or add "+1" even though the format is the same, just to satisfy this computer library code"

**Comment by catamphetamine** [comment]
I see, so you've fixed it.
Just to reiterate: validation and phone number input are completely different tasks and shouldn't be mixed and should be performed at different stages.

**Comment by catamphetamine** [comment]
For example, inputting a phone number is `AsYouType('US')`, and validating it for any country afterwards is `parsePhoneNumberFromString(asYouType.number).isValid()`.
