### ISSUE TITLE
parseNumber type definition doesn't consider invalid case

### ISSUE THREAD

**Issue by sman591** [catamphetamine/libphonenumber-js#371]
I noticed the following in the README for `parseNumber()`:

>parseNumber(text, [defaultCountry], [options])
>...
>If the phone number supplied isn't valid then an empty object {} is returned.

The invalid state here, where "an empty object {} is returned", isn't captured by the current TypeScript definition:

https://github.com/catamphetamine/libphonenumber-js/blob/7cf75a796a5cc11f4510ddb407fa8d025073cae1/custom.d.ts#L54

I'd like to propose changing this type to match the full return type of this function; something like:

```typescript
export function parseNumber(text: string, metadata: Metadata): ParsedNumber | {};
```

Is there a reason it isn't typed like this to begin with?

**Comment by catamphetamine** [comment]
> Is there a reason it isn't typed like this to begin with?

Me not using TypeScript.

I'll add the `| {}`, thx.

**Comment by sman591** [comment]
Cool! I wasn't sure if there was any historical reason behind it. Thanks for the quick response!

**Comment by catamphetamine** [comment]
By the way, `parseNumber()` has been deprecated for a while, and the new API is `parsePhoneNumberFromString()`.

**Comment by catamphetamine** [comment]
Should be fixed in the latest version.

**Comment by sman591** [comment]
Thank you!
