### ISSUE TITLE
Issue with Belarus telephone number validation

### ISSUE THREAD

**Issue by Pieter-1337** [catamphetamine/libphonenumber-js#373]
when entering a number for Belarus (which has a national prefix of '8') that also starts with an '8' after the country code (+375)  it's first occurence of 8  gets cut of.

**for example when entering +37582004910060 (img below)**

![Belarus1](https://user-images.githubusercontent.com/24230642/74147928-85683280-4c04-11ea-9786-bde7999831b0.png)

**Which is valid on your online validator (img below)**

![Belarus3](https://user-images.githubusercontent.com/24230642/74147939-8bf6aa00-4c04-11ea-98ec-2a8b0ec6cf7d.png)

 **the parseMax() function removes the first 8 which makes the number invalid... (img below)**

![Belarus2](https://user-images.githubusercontent.com/24230642/74147935-88fbb980-4c04-11ea-959a-e6cca9411ca5.png)

**Comment by catamphetamine** [comment]
Published libphonenumber-js@1.7.39
