### ISSUE TITLE
A bug in minified release

### ISSUE THREAD

**Issue by JacksonGL** [catamphetamine/libphonenumber-js#374]
In the [minified releases](https://github.com/catamphetamine/libphonenumber-js/releases), there is following code snippet (formatted for better illustration) that uses a variable before it was initialized:
```javascript
var v = n(12), 
    ...,
    E = '[' + O + ']{' + L + '}', // L is used
    ...,
    L = 2, ...  // but initialized here
```
I traced back to the [source](https://github.com/catamphetamine/libphonenumber-js/blob/99b14120506eb6d5932db82a49bf6dd3333c41c2/source/isViablePhoneNumber.js#L34):
```javascript
import {
    MIN_LENGTH_FOR_NSN,
    VALID_DIGITS,
    ...
} from './constants'

... 
const MIN_LENGTH_PHONE_NUMBER_PATTERN = '[' + VALID_DIGITS + ']{' + MIN_LENGTH_FOR_NSN + '}'
```
The concatenated string is used to construct a regex for matching phone numbers. It was supposed to be `/...[0-9０-９٠-٩۰-۹]{2}.../`; now it becomes `/...[0-9０-９٠-٩۰-۹]{undefined}.../`.
Looks like this is a bug in the minifier.

**Comment by catamphetamine** [comment]
I have replaced Webpack with Rollup.
See if the new version `libphonenumber-js@1.7.40` works.

**Comment by JacksonGL** [comment]
Looks like Rollup statically generates the string, which inlined ```MIN_LENGTH_FOR_NSN```. So it works :)
