### ISSUE TITLE
Support for Pitcairn and US Minor Outlying Islands

### ISSUE THREAD

**Issue by daveoap** [catamphetamine/libphonenumber-js#377]
Hi,

Would it be possible to add support for Pitcairn and US Minor Outlying Islands.

Thanks,
Dave

**Comment by catamphetamine** [comment]
https://github.com/google/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml

     Known omissions:

     * French Southern Territories (id="TF" countryCode="262"). This is not covered due to lack of information about its numbering plan. It has 140
       temporary inhabitants.

     * Pitcairn Island (id="PN") .This is not supported since evidence seems to be that the 50 inhabitants use satellite
       phones.

     See also:
       https://github.com/google/libphonenumber/blob/master/FAQ.md#unsupported

US Minor Outlying Islands are also not in the list.
Contact Google for any metadata issues.
