### ISSUE TITLE
 wrong mobile phone +33143802769 

### ISSUE THREAD

**Issue by tema1411** [catamphetamine/libphonenumber-js#379]
Hello. Can you say please,  why mobile phone +33143802769 (FR, mobile) is wrong?

I use: 
`libphonenumber.parsePhoneNumberFromString('+33143802769').isValid()`
and 
`<script src="https://unpkg.com/libphonenumber-js@1.7.6/bundle/libphonenumber-mobile.js"></script>`

**Comment by catamphetamine** [comment]
Hello.
See the "Bug reporting" section of the readme.
If the issue persists, you may re-post it.
