### ISSUE TITLE
Israel fixed line phone considered invalid

### ISSUE THREAD

**Issue by shiberz** [catamphetamine/libphonenumber-js#380]
This error appears only with mobile data pack, min and max packages behaves as expected.

```
import { parsePhoneNumberFromString } from 'libphonenumber-js/mobile';
parsePhoneNumberFromString('+97239121111').isValid() 
```
actual result: false
expected: true

[Google](https://libphonenumber.appspot.com/phonenumberparser?number=%2B972+3+9121111&country=IL).

**Comment by catamphetamine** [comment]
> Israel fixed line phone considered invalid

> This error appears only with mobile data pack

Well, what did you expect.

Also, the readme explicitly tells that `mobile` data is only for mobile numbers.
