### ISSUE TITLE
Include `leading digits` in result

### ISSUE THREAD

**Issue by dr3** [catamphetamine/libphonenumber-js#387]
## Steps to reproduce

Calling `getCountryCallingCode` on countries/territories like `American Samoa` and `Anguila`

## Observed result

It returns `+1`

## Expected result

What's the expected result?

It returns `+1 684` and `+1 264` respectively 

## Google's demo link

https://libphonenumber.appspot.com/phonenumberparser?number=%2B1-2641234567

**Comment by catamphetamine** [comment]
Hi.
First, the country calling code is `+1`, not `+1684`, even when `leadingDigits` are `684`.
Second, not all countries have `leadingDigits`: for example, `CA`nada.
https://github.com/google/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml
So `leadingDigits` are just an internal performance optimization in the library code, not an exposed feature.
