### ISSUE TITLE
phone number validation error

### ISSUE THREAD

**Issue by arthutox** [catamphetamine/libphonenumber-js#390]
## Steps to reproduce

pls try check this number +856 20 57 777 777
https://catamphetamine.gitlab.io/libphonenumber-js/

## Observed result

and you will see Valid: false
but if you try +856 20 77 777 777, Valid: true
this is strange, the first number is definitely valid.

## Expected result

I think the result should be valid. +856 20 57 777 777

## Google's demo link

https://libphonenumber.appspot.com/phonenumberparser?number=%2B856+20+57+777+777

**Comment by catamphetamine** [comment]
Google's demo says "Valid: false", so the result is correct.
