### ISSUE TITLE
[Feature Request] Falkland Islands Country Code

### ISSUE THREAD

**Issue by eileen-jiang** [catamphetamine/libphonenumber-js#394]
We currently use this library to display a dropdown of international country codes to users wanting to enter their phone numbers. However, the Falkland Islands are not supported, and we've received a request to allow for their country code. Please add support for this region in. Thank you!

**Comment by catamphetamine** [comment]
the Falkland Islands are supported

**Comment by eileen-jiang** [comment]
Thanks for your response! Can I ask where the list of supported countries is listed? I've been trying to find the file for awhile in the repo and can't find it.

**Comment by catamphetamine** [comment]
In this file:
https://github.com/catamphetamine/libphonenumber-js/blob/master/PhoneNumberMetadata.xml

It's huge

**Comment by eileen-jiang** [comment]
Hahah, it is. Thanks!
