### ISSUE TITLE
Getting all country flags, country names and country codes.

### ISSUE THREAD

**Issue by hayden664** [catamphetamine/libphonenumber-js#395]
Hi, I have a contact number field in a form that I'd like to loop out all flags, country name, and country code in a dropdown and after selected, the dropdown will display the flags only.

The "With country select" is what I want to achieve, like how it is here: [https://catamphetamine.gitlab.io/react-phone-number-input/](https://catamphetamine.gitlab.io/react-phone-number-input/).

I can only get all the country codes out at this point using getCountries(). But I can't seem to find how to loop out the flags and country names along with the country codes. Please help!

My code is available in stackoverflow. You can run the code snippet [there](https://stackoverflow.com/questions/65184595/adding-flags-and-country-name-into-select-drop-down-libphonenumber-js).

**Comment by catamphetamine** [comment]
What?

**Comment by hayden664** [comment]
I am sorry it kind of went out of format, please let me edit it for awhile

**Comment by catamphetamine** [comment]
It's still not clear what exactly do you want.

**Comment by hayden664** [comment]
Hi so sorry for the misinterpretation. But I have edited it clearly now so that you can understand. :)

**Comment by catamphetamine** [comment]
> Hi so sorry for the misinterpretation. But I have edited it clearly now so that you can understand. :)

Ahhh.
Okay, let's start from the start:

> I have a contact number field in a form that I'd like to loop out all flags, country name, and country code in a dropdown and after selected, the dropdown will display the flags only.

Can you decypher that phrase?

**Comment by hayden664** [comment]
Yea sure. So it is a contact number input field with a dropdown preppended in front. In the dropdown I want to show the country flags and country names. Then after the option is selected, I want to only display the country flag there.

**Comment by catamphetamine** [comment]
> Yea sure. So it is a contact number input field with a dropdown preppended in front. In the dropdown I want to show the country flags and country names. Then after the option is selected, I want to only display the country flag there.

Your writing is a kinda bizzarre.
I won't be reading your comments here anymore.
So I guess you're on your own.

**Comment by hayden664** [comment]
Dropdown:
![image](https://user-images.githubusercontent.com/72339835/101443170-bebe1b80-3957-11eb-862f-908fdf803824.png)

Output:
![image](https://user-images.githubusercontent.com/72339835/101443194-cb427400-3957-11eb-9f2e-70e97d066356.png)

Please have a look at these 2 images.

**Comment by hayden664** [comment]
> > Yea sure. So it is a contact number input field with a dropdown preppended in front. In the dropdown I want to show the country flags and country names. Then after the option is selected, I want to only display the country flag there.
> 
> Your writing is a kinda bizzarre.
> I won't be reading your comments here anymore.
> So I guess you're on your own.

I'm sorry that I caused confusion. But I would really need your help :(

**Comment by catamphetamine** [comment]
> I'm sorry that I caused confusion. 

Don't be.

> But I would really need your help

Life doesn't always give us what we want.
It's the cruel reality of this world.

**Comment by hayden664** [comment]
> > I'm sorry that I caused confusion.
> 
> Don't be.
> 
> > But I would really need your help
> 
> Life doesn't always give us what we want.
> It's the cruel reality of this world.

It just feels a bit of waste that the solution is already there in the demo but I can't implement it..
