### ISSUE TITLE
Swedish numbers issue

### ISSUE THREAD

**Issue by TitusEntertainment** [catamphetamine/libphonenumber-js#396]
## Steps to reproduce

Parse a Swedish phone number with

In Sweden it's common practice to remove the first digit 0 after +46.

Example +46 070 512 61 12

## Observed result

Returns as not not valid.

## Expected result

What's the expected result?

Expected result is to receive this as successful and the .number value to have an added 0 in the beginning.

## Google's demo link

Returns:

Phone Number entered: +46 07+ 512 61 12
defaultCountry entered: SE
Language entered: se-SE
Error type: NOT_A_NUMBER. The string supplied did not seem to be a phone number. 

![image](https://user-images.githubusercontent.com/16852656/104934277-3d23c980-59aa-11eb-87e5-ab463bbd939e.png)

**Comment by TitusEntertainment** [comment]
Forget I ever posted this :)

**Comment by TitusEntertainment** [comment]
Or actually, I get successful on the demo page, but not in the code.

My check is simple.

```ts
    import parsePhoneNumberFromString, { E164Number, PhoneNumber } from "libphonenumber-js";


    const phoneNumber: PhoneNumber | undefined = parsePhoneNumberFromString(_phoneNumber);
```

![image](https://user-images.githubusercontent.com/16852656/104934485-79572a00-59aa-11eb-9d2f-a7d03fbecd5a.png)

**Comment by TitusEntertainment** [comment]
This is what I posted, but you say there's a second demo. I must have missed that.

This is the URL: https://libphonenumber.appspot.com/phonenumberparser?number=%2B46+70+512+61+12&country=SE&geocodingLocale=se-SE

![image](https://user-images.githubusercontent.com/16852656/104935283-51b49180-59ab-11eb-90c4-2f68bfc8ceef.png)

**Comment by catamphetamine** [comment]
Your issue description is not valid.
You're passing different numbers.
Re-create the issue, I'm closing this one because it's become offtop.

**Comment by TitusEntertainment** [comment]
Alright, I'll make a new issue and will provide further info :)
