### ISSUE TITLE
Implement Telephone_numbers_in_Ivory_Coast 

### ISSUE THREAD

**Issue by lordgape** [catamphetamine/libphonenumber-js#397]
Any plans to implement https://en.wikipedia.org/wiki/Telephone_numbers_in_Ivory_Coast before Jan 31st 2021 ?

Ivory Coast is moving from 8 digits to 10 digit numbers.

**Comment by catamphetamine** [comment]
Ask Google: this library is simply a port of Google's library, so ask them if they implement something like that.

**Comment by josemsantos** [comment]
Hello,
Google did the update yesterday, they now support CI numbers, @catamphetamine when will be the next update here too?
Thank you

**Comment by catamphetamine** [comment]
Updated metadata to the latest version.
`libphonenumber-js@1.9.9`.
Reopen if there're any issues.
