### ISSUE TITLE
Question: is it possible to get geolocation out of a number, using this library?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [catamphetamine/libphonenumber-js#398]
So far I've seen only this library offering it (for free):
https://mvnrepository.com/artifact/com.googlecode.libphonenumber/geocoder
Demo:
https://libphonenumber.appspot.com/

There are some online services too, like these :
https://www.allareacodes.com/area-code-lookup/
https://www.ipqualityscore.com/phone-number-validator

I've found some libraries that might have it, but they are quite old. Newest one I've found is this:
https://github.com/BlueRival/node-areacodes

But I don't see on the demo here that it's possible.

**Comment by catamphetamine** [comment]
Hi.
If something like that was a feature, it would have to be a separate library, because otherwise (hypothetically) the metadata would be larger, and people already complain about the bundle size.

**Comment by AndroidDeveloperLB** [comment]
@catamphetamine I guess... Google does it too, as a "bonus", optional library, to the original one.
Is it a hard thing to do? Where do you get the data from?
Where does Google get the data from?
Where would this kind of information (the geolocation) would be from?
Can you please consider adding such a library?

**Comment by catamphetamine** [comment]
> Where do you get the data from?

If you meant phone number metadata, then it's that file:
https://github.com/google/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml

> Where does Google get the data from?

> Where would this kind of information (the geolocation) would be from?

You could ask them.

> Can you please consider adding such a library?

Do it yourself.

**Comment by AndroidDeveloperLB** [comment]
OK thanks and sorry if this made you upset.

**Comment by catamphetamine** [comment]
> sorry if this made you upset.

It surely didn't.

**Comment by AndroidDeveloperLB** [comment]
OK have a nice day :)

**Comment by catamphetamine** [comment]
Hmm, you too )
