### ISSUE TITLE
phone numbers from Ivory Coast (countryCode :  CI )

### ISSUE THREAD

**Issue by Yves97** [catamphetamine/libphonenumber-js#399]
The numbers in Ivory Coast have increased to 10 digits and those with all mobile operators.
In the past they were numbered with 8 digits
For more information please see this link.
https://fr.wikipedia.org/wiki/Liste_des_indicatifs_t%C3%A9l%C3%A9phonique_en_C%C3%B4te_d%27Ivoire

**Comment by catamphetamine** [comment]
You can report metadata bugs to Google.
https://github.com/catamphetamine/libphonenumber-js#bug-reporting
