### ISSUE TITLE
Eslint issue when using max or mobile metadata

### ISSUE THREAD

**Issue by JerryBels** [catamphetamine/libphonenumber-js#404]
## Steps to reproduce

import parsePhone from 'libphonenumber-js/mobile';

## Observed result

ESLint: 'libphonenumber-js-mobile' should be listed in the project's dependencies. Run 'npm i -S libphonenumber-js-mobile' to add it(import/no-extraneous-dependencies)

## Expected result

What's the expected result?

No Eslint error I guess?

**Comment by catamphetamine** [comment]
Looks like a duplicate of https://gitlab.com/catamphetamine/libphonenumber-js/-/issues/40
You can ask about it somewhere in ESLint repo issues.

**Comment by JerryBels** [comment]
Okay I will. Thank you for your help!
