### ISSUE TITLE
[Feature] Could we know why the phone number is not possible?

### ISSUE THREAD

**Issue by remi-blaise** [catamphetamine/libphonenumber-js#406]
Hi!

It would be great to be able to retrieve the reason why the function `isPossible()` fails.
Is phone number too short, too long for the country, ...

Let me know if it is possible or planned to be added to the library.

Thank you for your time,
Remi

**Comment by catamphetamine** [comment]
The `isPossible()` function only checks number length, as stated in the readme.

**Comment by catamphetamine** [comment]
https://github.com/catamphetamine/libphonenumber-js#ispossible-boolean

**Comment by remi-blaise** [comment]
Yeah I know that, I was advocating for a new feature.

**Comment by catamphetamine** [comment]
> Yeah I know that, I was advocating for a new feature.

Read the text from link I've provided.
It should be self-explanatory.

**Comment by catamphetamine** [comment]
@remi-blaise Oh, you wanted to know whether it's short or long.

**Comment by catamphetamine** [comment]
Published `libphonenumber-js@1.9.26`.

https://gitlab.com/catamphetamine/libphonenumber-js#validatephonenumberlengthinput-string-string

**Comment by remi-blaise** [comment]
You are amazing, great feature, thanks!

**Comment by remi-blaise** [comment]
I used the feature in my app, it works great!
