### ISSUE TITLE
Get the template/pattern for the phonenumber

### ISSUE THREAD

**Issue by phun-ky** [catamphetamine/libphonenumber-js#408]
Hi! I need to get the pattern/template for the current country selected. as in:

```javascript

import {getTemplate} from  'libphonenumber-js';
const _country = 'NO';
const _placeholder = getTemplate(_country);
input.placeholder = _placeholder;


```

Will result in input placeholder: `000 00 000` or `123 45 678`

Or a regex so we can use in custom validation.

**Comment by catamphetamine** [comment]
There's no single pattern for a country

**Comment by phun-ky** [comment]
Ehm, how is it validated then? Do not close before issue is resolved please. You already have the template, why can't ot be assigned oer country? Sendt fra min Galaxy
-------- Opprinnelig melding --------Fra: Nikolay ***@***.***> Dato: 09.07.2021  13:58  (GMT+01:00) Til: catamphetamine/libphonenumber-js ***@***.***> Ko: Alexander Vassbotn Røyne-Helgesen ***@***.***>, Author ***@***.***> Emne: Re: [catamphetamine/libphonenumber-js] Get the template/pattern for the phonenumber (#408) 
There's no single pattern for a country
