### ISSUE TITLE
Phone number in Somalia can be 9 digits long

### ISSUE THREAD

**Issue by SamsonovaJulia** [catamphetamine/libphonenumber-js#409]
## Steps to reproduce

I use your library and have an issue with long of the phone number for Somalia ('SO').

## Observed result

I would like to sign in with my mobile phone. And my somalian number consists of 9 digits without country code. In your examples.mobile.json somalian number consists of 8 digits. So I can not type all digits

## Expected result

I can put the number +252 123 123 123 and it should be valid

## Google's demo link

A link to the wikipedia page. It shows that phone number in Somalia can be 9 digits long:
https://en.wikipedia.org/wiki/Telephone_numbers_in_Somalia

Could you please add one more digit for Somalia ('SO')? Thanks

**Comment by catamphetamine** [comment]
Follow the instructions in the "Bug reporting" section:
https://github.com/catamphetamine/libphonenumber-js#bug-reporting

Reopen in that case.
