### ISSUE TITLE
Difference between `parsePhoneNumber` and `parsePhoneNumberFromString` ?

### ISSUE THREAD

**Issue by popod** [catamphetamine/libphonenumber-js#411]
In the readme `parsePhoneNumber` and `parsePhoneNumberFromString` are used, but only `parsePhoneNumberFromString ` is describe in the API section.

What is the difference between this two functions ?

I've done some tests and it seems that `parsePhoneNumber` need a `try/catch` block to catch errors and that `parsePhoneNumberFromString` return an empty response in case of error..

Thank you for reply

**Comment by catamphetamine** [comment]
The readme says:

```
parsePhoneNumberFromString(string, [options or defaultCountry]): PhoneNumber

Parses a phone number from string.

Can be imported both as a "default" export and as a "named" export.
```

**Comment by catamphetamine** [comment]
There doesn't seem to be anywhere in the README where `parsePhoneNumber` named export is used.

**Comment by popod** [comment]
here for example : https://github.com/catamphetamine/libphonenumber-js#use

**Comment by catamphetamine** [comment]
It's not a named export

**Comment by popod** [comment]
Thank you for reply, but this is not clear..

`import parsePhoneNumber from 'libphonenumber-js'` seems to works the same as `import parsePhoneNumberWithError from 'libphonenumber-js'` but not like `import parsePhoneNumberFromString from 'libphonenumber-js'` ?

What does or how works : `import parsePhoneNumber from 'libphonenumber-js'` (this is not documented)

I think that this could be better explained in the doc ?

**Comment by catamphetamine** [comment]
You seem to be confusing "default" exports and "named" exports.
https://medium.com/@etherealm/named-export-vs-default-export-in-es6-affb483a0910

**Comment by popod** [comment]
thank you for reply.. yes this is my bad.. I understand "default" and "named" exports.. but in my tests I'm using `require`..

```js
const libphonenumber = require('libphonenumber-js')

libphonenumber.parsePhoneNumber() // seems to works like parsePhoneNumberWithError()
libphonenumber. parsePhoneNumberFromString()
```

This two functions doesn't works the same.. and this is because of that that I ask a `parsePhoneNumber` documentation.

But this is okey and all works when using `import`. Sorry for that !
