### ISSUE TITLE
German phone number starting with letter is seen as valid

### ISSUE THREAD

**Issue by kasium** [catamphetamine/libphonenumber-js#416]
## Steps to reproduce

```js
parsePhoneNumberFromString('a123321312321', 'DE')
```

## Observed result

isValid returns true

## Expected result

isValid should return false. The demo also returns true.

## Google's demo link

Google returns this result: https://libphonenumber.appspot.com/phonenumberparser?number=a123321312321&country=DE&geocodingLocale=de-DE. Seems like isValidNumber returns false.

**Comment by catamphetamine** [comment]
> Number is valid.

What did you mean by that

**Comment by kasium** [comment]
Sorry, corrected. Meant that isValid returns true

**Comment by catamphetamine** [comment]
https://github.com/catamphetamine/libphonenumber-js#isvalid-boolean

**Comment by kasium** [comment]
Thanks. I was not aware of that!
