### ISSUE TITLE
Length of international phone number in Bulgaria

### ISSUE THREAD

**Issue by IgorSushko1** [catamphetamine/libphonenumber-js#419]
Hello! Install the last versioin of library - 1.9.44 and have an problem - we have international client from Bulgaria, and he wrote a phone into form but the length of number in library is 8, but according this article the right number of phone - is 
 9 (https://en.wikipedia.org/wiki/Telephone_numbers_in_Bulgaria)

**Comment by catamphetamine** [comment]
See [bug reporting](https://github.com/catamphetamine/libphonenumber-js#bug-reporting)
