### ISSUE TITLE
Deprecated formats raise an error

### ISSUE THREAD

**Issue by maximevast** [catamphetamine/libphonenumber-js#423]
## Issue

`National` and `International` formats are typed as deprecated [here](https://github.com/catamphetamine/libphonenumber-js/blob/27eb2e7749f7fa8ff3133453d553f17738d70ef5/types.d.ts#L42)

But they raise an error when used [here](https://github.com/catamphetamine/libphonenumber-js/blob/d403791f3b28747564fe735b285b999aa2129c7a/source/format_.js#L108)

## Proposed solution

Update the types so users know at build time that they are using invalid values

I can open a pull request if you are happy with this proposal.

Thanks

**Comment by catamphetamine** [comment]
Hmm, indeed: deprecated formats can be removed from typings.

Removed from typings. Some future release will include those.
Thx.
