### ISSUE TITLE
Australian numbers are invalid

### ISSUE THREAD

**Issue by 4riel** [catamphetamine/libphonenumber-js#430]
Hey there!, I noticed that some australian phone numbers gave an isValidNumber() : false result in this library when google's library returns it's valid.

For example: +61493523724
https://libphonenumber.appspot.com/phonenumberparser?number=+61493523724&country=AU

They're mostly from the same providor Telstra, and I'm guessing they're new numbers. Maybe it's missing some metadata update in the javascript library?

**Comment by catamphetamine** [comment]
Hi. 
See https://github.com/catamphetamine/libphonenumber-js#bug-reporting
