### ISSUE TITLE
isValid() and isValidPhoneNumber() return real phone number is invalid

### ISSUE THREAD

**Issue by xxv202** [catamphetamine/libphonenumber-js#431]
Hi, I'm using isValid() to check if my input phone number is valid or not. But recently I found an issue with these special number. Phone number formatted for Australia that has the number starts with:
+ 61 493 xxx xxx

+ 61 493 5xx xxx
+ 61 493 6xx xxx
+ 61 493 7xx xxx
+ 61 493 8xx xxx
+ 61 493 9xx xxx

+ 61 494 xxx xxx
+ 61 495 xxx xxx
+ 61 496 xxx xxx
does not recognized as correct formatted phone number, even though these are legit number allowed in Australia.

I read the document about full metadata set, I entered these type of number on the demo page https://catamphetamine.gitlab.io/libphonenumber-js/ but it's not working at all. I also tried isValidPhoneNumber() method but it returned invalid. Is there something wrong with the regex in metadata set? 
I'm using "libphonenumber-js": "^1.7.14". Thanks

**Comment by catamphetamine** [comment]
Hi. See the [bug reporting](https://github.com/catamphetamine/libphonenumber-js#bug-reporting) section of the readme.
