### ISSUE TITLE
Get countryCode, countryName, countryFlag object

### ISSUE THREAD

**Issue by ankit-gl** [catamphetamine/libphonenumber-js#441]
I want to develop custom country picker for input field and wanted to list the countries with their name, flag and country code. Could not find a way to get these data.

```getCountries``` on returns countryCode, but wanted the name and flag too.

**Comment by catamphetamine** [comment]
There're no names or flags in this repo.

Flags could be looked up in `country-flag-icons`.

Names could be read from `react-phone-number-input`.

**Comment by bryanltobing** [comment]
i'm using `react-native` so using `react-phone-number-input` that is based on html and css is not an option. is it possible to export only the utils to get the value.

i'm thinking creating something like `getCountryCallingCode(countryCode)`

maybe 
- `getCountryName(countryCode)`
- `getCountryFlag(countryCode)`

**Comment by catamphetamine** [comment]
You haven’t read any pf the readmes. How’re you even in the profession.
I’ll block you. Also, there is a React Native component in
reach-phone-number-input.

**Comment by bryanltobing** [comment]
Thanks
