### ISSUE TITLE
isValidPhoneNumber function return wrong result

### ISSUE THREAD

**Issue by thanhbinh0995** [catamphetamine/libphonenumber-js#442]
I used this website  to check phone number 2949491 in IR and it return valid = false
https://catamphetamine.gitlab.io/libphonenumber-js/?parseCountry=IR&parseValue=2949491&asYouTypeCountry=US&findNumbersCountry=US&findNumbersText=For%20more%20details%20call%20%2B7%20(800)%20555-35-35%20internationally%20or%20reach%20the%20local%20US%20branch%20at%20(213)%20373-4253%20ext.%201234%20for%20paid%20customer%20support.

<img width="906" alt="image" src="https://user-images.githubusercontent.com/12002632/236994452-37c6d42b-5255-4d43-ad41-77982173dfe4.png">

but function isValidPhoneNumber return true

<img width="524" alt="image" src="https://user-images.githubusercontent.com/12002632/236996604-f49dc035-a18e-4d10-9919-eec1d0c52938.png">

<img width="297" alt="image" src="https://user-images.githubusercontent.com/12002632/236996631-5d1bee53-d95d-4cbc-b15a-9538724ec411.png">

can you check this issue?
thanks

**Comment by catamphetamine** [comment]
See the "Note: " in your screenshot. 
Import from `libphonenumber-js/max`.
