### ISSUE TITLE
+15575001171 number not validated as valid phone number when it is valid by Google's libphonenumber

### ISSUE THREAD

**Issue by norkhairi** [catamphetamine/libphonenumber-js#443]
As per title, the phone number seems to be valid when tested with Google's libphonenumber package but not with libphonenumber-js

**Comment by catamphetamine** [comment]
Nowhere does it say that the demo page is on `github.io`. Or does it? Where did you get that link?

**Comment by catamphetamine** [comment]
The demo page says "Valid".
![image](https://github.com/catamphetamine/libphonenumber-js/assets/477167/8a44973b-e2f8-4e9d-a14b-71bb3cd979b0)
