### ISSUE TITLE
Unable to delete characters if there is a parenthesis

### ISSUE THREAD

**Issue by yashkothari** [catamphetamine/libphonenumber-js#447]
If I hold backspace, characters are deleted until the parenthesis. If I press the left arrow key, I can then delete all characters

https://github.com/catamphetamine/libphonenumber-js/assets/6384914/b0d28983-3d95-4d89-a444-eeda2f9f5bf5

**Comment by catamphetamine** [comment]
That's irrelevant to this library.

https://github.com/catamphetamine/libphonenumber-js/issues?q=is%3Aissue+parenthesis
