### ISSUE TITLE
Different Results | Real Life vs Demo

### ISSUE THREAD

**Issue by orangehaired** [catamphetamine/libphonenumber-js#449]
Hi, 

When testing a number in the demo it claims that it is not valid.  In my code, it claims to be valid.  I'm not sure if this is a bug or my fault.

Demo: 
![](https://i.ibb.co/6srDxWj/Screenshot-2023-11-10-at-00-45-35.png) - Full Image:  https://i.ibb.co/6srDxWj/Screenshot-2023-11-10-at-00-45-35.png

Production Code: 
![](https://i.ibb.co/pWXcD2g/Screenshot-2023-11-10-at-00-46-13.png)  Full Image: https://i.ibb.co/pWXcD2g/Screenshot-2023-11-10-at-00-46-13.png

**Comment by catamphetamine** [comment]
Maybe you’re using not the /max metadata

**Comment by orangehaired** [comment]
Worked with max metadata. Thx @catamphetamine
