### ISSUE TITLE
validatePhoneNumberLength does not return TOO_LONG for invalid Ukrainian phone number 

### ISSUE THREAD

**Issue by DavidArutiunian** [catamphetamine/libphonenumber-js#450]
A valid Ukrainian phone number includes 9 digits after `+380` country code. I'm validating phone number with `libphonenumber-js` and getting invalid results when user types 10 digits. Question is why user is able to type 10 digits?

I didn't found any info that Ukrainian phone number can be 10 symbols long (after a country code)

```javascript
validatePhoneNumberLength("+380 93 111-111") // returns TOO_SHORT - it's ok
validatePhoneNumberLength("+380 93 111-1111") // returns undefined - it's ok
validatePhoneNumberLength("+380 93 111-11111") // returns undefined - it's not ok, should be TOO_LONG
validatePhoneNumberLength("+380 93 111-111111") // returns TOO_LONG - it's ok
```

**Comment by catamphetamine** [comment]
> Question is why user is able to type 10 digits?

This library doesn't provide any "typing" capabilities

**Comment by catamphetamine** [comment]
So what's your question then?

**Comment by catamphetamine** [comment]
@DavidArutiunian See the "bug reporting" section of the readme. There it explains how to check any assumptions using Google's demo.

**Comment by catamphetamine** [comment]
@DavidArutiunian According to the links you've posted, Google doesn't return `TOO_LONG` for those numbers so `libphonenumber-js` behavior is correct.

**Comment by catamphetamine** [comment]
@DavidArutiunian And when it's too long then it returns `TOO_LONG`:
https://libphonenumber.appspot.com/phonenumberparser?number=%2B38093111111111

**Comment by DavidArutiunian** [comment]
Ok, I see. Thanks for clarification! Closing this issue.
