### ISSUE TITLE
Cuba added a new prefix 63 to phone number

### ISSUE THREAD

**Issue by MandyMF** [catamphetamine/libphonenumber-js#452]
Cuba phone numbers have the structure +53 5..... with length 8 without counting country code, and now can also be +53 63.... with length 8 without counting country code. Now Cuba phone numbers can start with 5 or 63.
https://www.dimecuba.com/revista/noticias-cuba/nueva-numeracion-celulares-cuba/

**Comment by catamphetamine** [comment]
Hi. You could create an issue at Google if you'd like:
https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md

This library uses Google's metadata.
