### ISSUE TITLE
Unable to get Number Type of some numbers like Indian Mobile Numbers

### ISSUE THREAD

**Issue by tahseen0amin** [catamphetamine/libphonenumber-js#455]
I am getting NumberType as undefined for some of the following numbers:

1.  9821121775 - IN
2. 1234567899 - IN

But in the google libphonenumber return the correct Number Type.
[https://libphonenumber.appspot.com/phonenumberparser?number=9821121775&country=IN](https://libphonenumber.appspot.com/phonenumberparser?number=9821121775&country=IN)

**Comment by catamphetamine** [comment]
Most likely you’re not using max metadata

**Comment by tahseen0amin** [comment]
How do we do that?

This is how I am using it
```typescript
import { parsePhoneNumberWithError } from 'libphonenumber-js';

const phoneNumberObj = parsePhoneNumberWithError(
        phoneNumber,
        selectedCountryAbbr,
      );
valid = phoneNumberObj.isValid();
const type = phoneNumberObj.getType();
if (type && type !== 'MOBILE') {
    valid = false;
}
```

Where do I need to change that.

**Comment by catamphetamine** [comment]
`from 'libphonenumber-js/max'`

**Comment by tahseen0amin** [comment]
Thanks.

Closing this issue.
