### ISSUE TITLE
Missing dashes when using International format

### ISSUE THREAD

**Issue by sylvhama** [catamphetamine/libphonenumber-js#457]
This issue is a repost of https://github.com/catamphetamine/libphonenumber-js/issues/163 while respecting the suggested [bug formatting](https://github.com/catamphetamine/libphonenumber-js#bug-reporting).

On this [libphonenumber-js demo page](https://catamphetamine.gitlab.io/libphonenumber-js/?parseCountry=CA&parseValue=5144311489&asYouTypeCountry=US&findNumbersCountry=US&findNumbersText=For%20more%20details%20call%20%2B7%20(800)%20555-35-35%20internationally%20or%20reach%20the%20local%20US%20branch%20at%20(213)%20373-4253%20ext.%201234%20for%20paid%20customer%20support.) you can notice that the Canadian phone number `5144311489` is formatted as `+1 514 431 1489` when picking International format.

On this [Google's demo page](https://libphonenumber.appspot.com/phonenumberparser?number=5144311489&country=CA) you can see that the same phone number will be formatted as `+1 514-431-1489` when looking at the International format row.

I would expect the same format as Google or maybe an option to use dashes instead of spaces.

**Comment by sylvhama** [comment]
It seems to only be an issue for US and Canadian phone numbers (+1 region).

**Comment by catamphetamine** [comment]
Hello. See the very beginning of the readme where it lists the differences.
This is one of them. Not a bug.

**Comment by catamphetamine** [comment]
“

   -

   Doesn't use hyphens or brackets when formatting international phone
   numbers, only whitespace (seems more logical this way).

   “
