### ISSUE TITLE
Leading 0 is removed for Brazilian numbers

### ISSUE THREAD

**Issue by iqHpi** [catamphetamine/libphonenumber-js#465]
```
$ console.log(parsePhoneNumber('+55 0-800-5700800').number)
+558005700800
```

Expected output is `+5508005700800`

**Comment by catamphetamine** [comment]
That's the expected behavior

**Comment by iqHpi** [comment]
But the number can't receive international calls when the leading 0 is removed.

**Comment by catamphetamine** [comment]
In that case, see
https://github.com/catamphetamine/libphonenumber-js?tab=readme-ov-file#bug-reporting
