### ISSUE TITLE
French landline numbers seems not working

### ISSUE THREAD

**Issue by KASOGIT** [catamphetamine/libphonenumber-js#469]
Hi, here a valid french landline number: +33565309445
https://libphonenumber.appspot.com/phonenumberparser?number=+33565309445&country=FR

Calling `isValidPhoneNumber('+33565309445') === false`

Are u aware of this ? Is that normal ?

Thanks

**Comment by catamphetamine** [comment]
Hi. See “bug reporting” section of the readme

**Comment by KASOGIT** [comment]
@catamphetamine Yes totally my bad, i wasn't using the max metadata. Thanks again !
