### ISSUE TITLE
Phone number +92 339 1792739 is incorrectly validated

### ISSUE THREAD

**Issue by AzkaNoreen6** [catamphetamine/libphonenumber-js#472]
Phone number +92 339 1792739 is incorrectly validated as valid in libphonenumber-js whereas 339 is not a valid network code , phone number having network code 338 is correctly validated as false as 338 is not valid network code, 
So phone numbers having 339 should also be invalid.

**Comment by catamphetamine** [comment]
See “bug reporting” section of the readme
