### ISSUE TITLE
Madagascar Format Issue

### ISSUE THREAD

**Issue by Cezar-Duarte-UWT** [catamphetamine/libphonenumber-js#474]
A client put their phone # in this format +261386187546 and the script is marking as invalid...

It does let you proceed if you put 7 digits... how can I let this number pass through if it has 9 digits for Madagascar?

**Comment by catamphetamine** [comment]
Not clear. See "Bug reporting" section of the readme.

**Comment by Cezar-Duarte-UWT** [comment]
Hi @catamphetamine according to Google and your script, Madagascar has 7 digits (plus the area code) but... we have a client from Madagascar where his phone number has 9 digits plus the area code and it is invalid according to your script.

**Comment by catamphetamine** [comment]
Hi. See again the "Bug reporting" section of the readme. There're instructions on how to submit bug report.

**Comment by Cezar-Duarte-UWT** [comment]
Can u let me know what's the most current version? I have this one on Angular Package ^1.9.19
