### ISSUE TITLE
ZA Number 075 / 275 pass validation

### ISSUE THREAD

**Issue by ReturnXDev** [catamphetamine/libphonenumber-js#476]
So these were picked up by a third party tool we send leads to because they passed our validation and failed on their's.

So in South Africa we don't have numbers that start with 075 / 275 so a number like 0751111111 would pass this libs validation but in reality it doesn't exist.

Some proof:
- https://mybroadband.co.za/news/cellular/541169-south-africas-new-telephone-and-cellphone-number-codes.html
- https://mybroadband.co.za/news/telecoms/165706-telephone-and-cellphone-number-codes-in-south-africa.html
- https://en.wikipedia.org/wiki/Telephone_numbers_in_South_Africa

I know this is a rewrite of Google Android as you say, should I rather create the issue on their repo?

**Comment by catamphetamine** [comment]
See https://github.com/catamphetamine/libphonenumber-js?tab=readme-ov-file#bug-reporting
