### ISSUE TITLE
Issue with asYouType and invalid phone numbers

### ISSUE THREAD

**Issue by mahyarr** [catamphetamine/libphonenumber-js#98]
Hi there, I've been using this library in my project and it's been working great. Thanks for making it available.

There's however one issue with the asYouType functionality that I have not been able to work around.

If I enter a sequence of digits followed by a plus sign (e.g. 1234+) the formatter returns just the numbers (1234). Then any subsequent digit entered will result in an empty string (1234+5 => empty)

My expectation is that the moment the input starts looking like an invalid number, the formatter should just return the original input. At least this is how the dialpad on iPhone works.

**Comment by catamphetamine** [comment]
Not getting the behaviour you described.
On the demo page I can enter `1234+` and then `5` and it still retains the full number (except for the national prefix which is expected)
https://catamphetamine.github.io/libphonenumber-js/

**Comment by mahyarr** [comment]
Seems like on the demo page, you're explicitly stripping out plus signs if they are not at the beginning of the value before passing it on to the asYouType. I guess I could use the same technique. Thanks for your quick response.

```
parse={(character, value) =>
{
  // Leading plus is allowed
  if (character === '+')
  {
    if (!value)
    {
      return character
    }
  }

  // Digits are allowed
  return parseDigit(character)
}}
```

**Comment by catamphetamine** [comment]
It's not about the demo page.
Until you provide a test case illustrating the issue there's no proof that such an issue exists.
https://github.com/catamphetamine/libphonenumber-js/blob/master/test/as%20you%20type.js
